### ISSUE TITLE
consistent structure in VS build

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#101]
In hacking up the VS build files for #93 I noticed that of the 3 projects in the solution, one is an nmake file while the other two are ... whatever VS calls its XML config format. Consistency here would be a good way to lower the barrier to entry and help keep both builds working.

Specifically this means converting the SAPI project in the VS solution from an nmake to the VS XML build config.

**Comment by wcarthur1** [comment]
SAPI library uses a makefile so we can automate the make as much as possible.

For instance, I recently re-generated the SAPI library code from the specification (using my autogeneration code), and it resulted in some new marshalling and unmarshalling funcitons.

In an ordinary VS studio project file, I’d have to manually add those to the build, both release and debug.

Also, in the past, we’ve done massive changes to the sapi library directory structure, and these were much easier to account for with the makefile automatically finding the files, etc.

I’m all for consistency as much as possible, but in this case, I think the advantages outweigh the disadvantages.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by flihp** [comment]
Thx for the background @wcarthur1. I was assuming that the standard VS project would allow for something equivalent to subdir/*.c style (glob) references. If this is the case I'd agree with you.

Closing as won't fix.
