### ISSUE TITLE
rename tpm2tss with tss2

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#103]
Based on feedback from the TCG working group we need to make a few changes to the way we're naming include directories and libraries.

$(includedir)/tpm2tss -> $(includedir)/tss2
$(libdir)/libtpm2tss.so -> $(libdir)/libtss2.so

This will break all code that uses the TPM2.0-TSS currently. Apologies for punishing early adopters further.

**Comment by wcarthur1** [comment]
One correction below…

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by flihp** [comment]
yeah that was a typo, good catch & thanks
