### ISSUE TITLE
factor tpm20.h header

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#104]
This is a convenience header that pulls in other headers. Since we're installing it it should only reference other installed headers. Thus we probably have to break it up into two separate headers: the installed version will pull in other tss2 headers, the version that's not installed (probably named tpm20_util.h) will pull in everything else.

**Comment by wcarthur1** [comment]
Tpm20_util.h should not be available to normal apps.  It’s only for the use of tpmclient and tpmtest (although, I think tpmtest should remove all tests that depend on this).

You covered that below, when you said that it’s not installed, but I just wanted to emphasize this to be sure. It “pulls in everything else” that’s needed for tpmclient.cpp, not everything else needed for normal apps.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by flihp** [comment]
Yup yup. I'm actually thinking there's no need for the *util.h version of this header anyways. It looks like we only need to factor out 2 files and those are only used by the test programs. Better to just include those files in the tests directly IMHO. Reasonable?

**Comment by flihp** [comment]
I just ran into another interesting one:
The tcti_util.h file is one that we decided should not be installed. It defines a pile of structures that are specific to the Intel TCTIs. These are opaque blobs in the spec and only have meaning to specific TCTI implementations so I think we're right in that it doesn't belong with the tss2 headers.

AFAIK, it does need to be installed with the TCTI headers that we provide though. Consumers need to know what these structures are in order to use our TCTIs.

How do you feel about moving these structures, or maybe the whole file in with the other headers in $(includedir)/tcti ?

**Comment by wcarthur1** [comment]
That’s ok with me.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by wcarthur1** [comment]
Below…

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by flihp** [comment]
Consumers are required to populate structures like the TSS2_TCTI_CONTEXT no? This is opaque to the tss2 and all of its code but the structure has meaning to the TCTI implementation (not the interface). So this means that the guts of the TSS2_TCTI_CONTEXT structure (whatever they may be) must be populated by the consumer of a given TCTI.

I'm just starting to read the spec but I think this is a pretty common pattern. Then again, I may be missing the point so please excuse and explain if I'm in error. We can chat directly if that will make things easier. I'm happy to take notes and summarize for this thread.

**Comment by flihp** [comment]
I've been refactoring this in my head a bit and the recent work on the headers has me thinking that this needs to be broken out into a few more specific tickets.
