### ISSUE TITLE
use of API version macro

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#117]
We've currently got a macro that looks like it is / was intended to prevent different versions of the headers from being used simultaneously. It's defined in two places though which may cause confusion. See:

https://github.com/01org/TPM2.0-TSS/blob/master/include/tpm2sapi/tss2_common.h#L45
https://github.com/01org/TPM2.0-TSS/blob/master/include/tpm2sapi/tpm20.h#L32

The spec has a structure that is intended to track ABI versions, but this macro seems to be of our own invention. A few questions:

1. Of the two places above where this is defined, which is the right place? This of course assumes it should only be defined once. AFAIK since this isn't from the spec it shouldn't be defined in a tss2*.h file so I'd guess the convenience header (tpm20.h) is the right place.
2. Do we have a strategy for tracking spec versions here? Git history shows this value has never been changed.
3. I know these headers are generated from bits of the spec so I'm hesitant to submit PRs that rearrange anything in them as I don't want to disrupt the generation process. I'm assuming that the "right" way to change the headers is to update the script that generates them but I'm not sure how to go about doing so.

TIA

**Comment by theopolis** [comment]
IMO if you plan on distributing the TSS implementation as a library (or set of)-- say one day there will be a `/usr/lib/libtss2.so` and the like, then having the version define within the "entry point" include for the library is best. In the case of SQLite, `$PREFIX/include/sqlite3.h` includes the version defines. So going with `tpm20.h` seems reasonable. Apache Thrift includes a `$PREFIX/include/thrift/config.h` that has the string define and the integer equivalent.

Also, it's handy to include a symbol within shared objects for runtime decisions! A well placed:
```cpp
uint64_t kLibTssVersion = TSS2_API_VERSION_1_1_1_1;
```
wont hurt anyone and for the weird case where an application can(or needs) to make runtime decisions, it's super easy. 

Curious, what's the reasoning behind the appended `_1_1_1_1` on `TSS2_API_VERSION_1_1_1_1`? Seems like a well-known define/symbol where the value is the version is easier? Definitely easier in the build logic (autoconf/CMake), perhaps a matter of opinion if preprocessor `defined` or integral comparisons look cleaner.

**Comment by flihp** [comment]
Summarizing a conversation with Will:

1. As expected, tpm20.h is intended to be the entry point, this is where the macro should be defined. The other headers will check it. 
2. No plans currently
3. Submit patches, the tool that generates the headers will be updated to match the new format etc.
