### ISSUE TITLE
Still need to install some more head files 

### ISSUE THREAD

**Issue by gwei3** [01org/TPM2.0-TSS#125]
Below header files are used by resourcemgr/tpmclient/tpmtest and tpm2.0-tools, so need to install them into /usr/local/include too. Otherwise, tpm2.0-tools can't build.

endianConv.h
sys_api_marshalUnmarshal.h
sysapi_util.h
tcti_util.h

**Comment by flihp** [comment]
This needs to be solved in the tpm2.0-tools repo. IMHO, exposing non-standard APIs through the TSS library is not the solution we want. I've got a PR in the tools repo to solve this: https://github.com/01org/tpm2.0-tools/pull/29

@gwei3 : Please take a look at the PR above and see if it addresses the concerns you've raised here.

**Comment by gwei3** [comment]
you are right. I agree and merged your PR 01org/tpm2.0-tools#29

**Comment by flihp** [comment]
Many thanks @gwei3 :smile:
