### ISSUE TITLE
tpmtest fails intermittently with 0xa00a error.

### ISSUE THREAD

**Issue by wcarthur1** [01org/TPM2.0-TSS#135]
I/O error intermittently.

**Comment by wcarthur1** [comment]
Some more data on this:  it looks like a driver error.  I captured the error in a debug dump.  we're getting decimal 62 returned from a call to write of a CreatePrimary command from the resource manager to the linux device driver.  I have older driver code, so I need to update that, but since Philip's also been seeing the error, I doubt this will help.

**Comment by flihp** [comment]
I haven't seen this issue in practice in a long time. I don't know that it was actually fixed but it may have been remedied by some other change. I'm closing this issue and labeling it as "invalid". It may well resurface in the future but we'll deal with that when it happens.
