### ISSUE TITLE
allow users to set TCTI magic & version as part of API?

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#145]
Hey @wcarthur1, quick question:

I was looking through the device TCTI the other day and I'm trying to understand the logic behind the initialization function specifically w/r to the magic number and version data. We allow the user to provide these values but we then check on each call that these values are set to the values that we expect. The later part is the behavior I would expect. We want to be sure the user is passing the TCTI a context that the code can understand. Providing an API to users that allows them to set arbitrary values for these things however seems strange to me. Aren't we just giving them a way to shoot themselves in the foot?

I've coded up an example unit test to demonstrate what I mean here: https://github.com/flihp/TPM2.0-TSS/commit/45bd5dc0ded0d6f269d5e11e7fe2ec107c3b5ffe

My recommendation would be to change the API and not allow users to specify these values themselves. We should set them as part of initialization behind the scenes and continue to check them to be sure the context is one we can understand.

Let me know what you think & thanks!

**Comment by wcarthur1** [comment]
i agree with you--users shouldn't be able to set the TCTI magic and version.

**Comment by flihp** [comment]
Thanks @wcarthur1, marking this as a bug.
