### ISSUE TITLE
RM code to cleanup after connection dies

### ISSUE THREAD

**Issue by wcarthur1** [01org/TPM2.0-TSS#163]
Philip can you please look at my "connection_dies_cleanup" branch changes. 

I cleaned up and refactored this code, basing on the latest master code.  It currently builds and runs under Windows.  

I haven't yet done the work for Linux, because I want your input on platformcommand.c  I had to add a critical section to the non-SAPI_CLIENT version of this code.  So the questions are:
1.  Is use of SAPI_CLIENT #ifdef ok in this file?
2.  What about the three externs I declared:  StartCriticalSection, EndCriticalSection, tpmMutex?  I could make tpmMutex a global in resourcemgr.c and add externs to the criticalsection.c file.  this way I wouldn't have to pass in a pointer to tpmMutex to StartCriticalSection and EndCriticalSection.  But that doesn't solve the problem of the two externs for the functions.
3.  Anything else you see, please let me know.

**Comment by flihp** [comment]
I bounced https://github.com/01org/TPM2.0-TSS/pull/155 back in to your court (I think). Will pick this one up next.

**Comment by wcarthur1** [comment]
What am I supposed to do with #155—I still see 5 commits for this.  And I couldn’t see any new comments by you.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by flihp** [comment]
I sent you an email.

**Comment by wcarthur1** [comment]
I just got this code to build and run under Linux.  I might change it to a pull request pretty soon.  Any comments you can give me would be appreciated when you have time.

**Comment by flihp** [comment]
AFAIK this is in #172. Closing so we can have the discussion on that PR thread.
