### ISSUE TITLE
Autoconf error

### ISSUE THREAD

**Issue by jethrogb** [01org/TPM2.0-TSS#185]
When running `./bootstrap` I get:
```
Running autoconf ...
configure.ac:10: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```
The solution, which I found in [a similar issue](https://issues.mediagoblin.org/ticket/755#comment:5) is to change the line in `bootstrap` with `aclocal` to `aclocal -I m4 --install`.

**Comment by jethrogb** [comment]
Actually the real solution was to install the autoconf archive which is clearly mentioned as a dependency in the INSTALL file.

**Comment by edonyM** [comment]
Hi there, I encounter the same error and I follow your solution which is installing the autoconf archive and other dependencies listed. But I got the same error again.
* I download the latest package autoconf-archive-2016.03.20.tar.xz from http://mirror.hust.edu.cn/gnu/autoconf-archive/ and install it.
* I download the latest package cmocka-1.0.1.tar.gz from https://git.cryptomilk.org/projects/cmocka.git/ and install cmocka.
* I install autoconf, automake, libtool, gcc, gcc-c++, glibc, glibc-devel with `yum`.

Is there anything wrong about what I have done?

**Comment by edonyM** [comment]
* Linux localhost.localdomain 3.10.0-229.30.1.69.x86_64 #1 SMP Wed Jun 1 09:06:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* autoconf (GNU Autoconf) 2.69
* automake (GNU automake) 1.13.4
* m4 (GNU M4) 1.4.16
* libtool (GNU libtool) 2.4.2
