### ISSUE TITLE
failed to startup resource manager for PTT

### ISSUE THREAD

**Issue by hteh** [01org/TPM2.0-TSS#191]
downloaded the latest TPM TSS source, no issues when compile and build. however, resource manager couldn't start for PTT.

error message shown:
Initializing device TCTI Interface
Initializing Resource Manager
send failed with error: 88
Resource Mgr failed to initialize.  Exiting...

**Comment by wcarthur1** [comment]
Thanks for reporting this.
Can you try debugging into the resource manager to see what's going wrong.  Currently, I don't have a working system with Linux and a real TPM for me to debug this (my system died).  I'm working to get that remedied, but might be able to fix your problem more quickly if I had more information about what's going on.

**Comment by hexchain** [comment]
I have the same problem.

`sudo strace resourcemgr`:
```
write(1, "Initializing device TCTI Interfa"..., 35Initializing device TCTI Interface
) = 35
open("/dev/tpm0", O_RDWR)               = 3
write(1, "Initializing Resource Manager\n", 30Initializing Resource Manager
) = 30
sendto(0, "\0\0\0\1", 4, 0, NULL, 0)    = -1 ENOTSOCK (Socket operation on non-socket)
write(1, "send failed with error: 88\n", 27send failed with error: 88
) = 27
write(1, "Resource Mgr failed to initializ"..., 46Resource Mgr failed to initialize.  Exiting...) = 46
write(1, "\n", 1
)                       = 1
exit_group(1)                           = ?
+++ exited with 1 +++
```

However `/dev/tpm0` is a chardev:
```
crw------- 1 root root 10, 224 Apr 22 11:08 /dev/tpm0
```
