### ISSUE TITLE
Resource Manager hang

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#199]
I'm getting this second hand from a few different sources so this may not be completely accurate. Bear with me.

It looks like 3c0debc broke something when the resource manager is connected to a proper TPM instead of the simulator. That's my commit so I'm digging into this in the next few days.

**Comment by snits** [comment]
Hi Philip, that probably originated with me. With that commit, resourcemgr errors out when I run with a send failed error. I noticed that InitResourceMgr() has calls to PlatformCommand() with MS_SIM_POWER_ON and MS_SIM_NV_ON, but they aren't wrapped with a check for simulator. If I wrap the calls with if (simulator) then resourcemgr runs. I don't know if that is a solution though as I'm running into other issues running tpmtest with that in place. This is on a Lenovo t440s laptop.

**Comment by snits** [comment]
tpmtest also has some PlatformCommand() calls that aren't wrapped by any checks.

**Comment by flihp** [comment]
Hey @snits, thanks for the additional data. It looks like this was reported before as well in #191. Looks like that was closed w/o a resolution ¯\_(ツ)_/¯

I'll take a dig into this in the next few days.

**Comment by gwei3** [comment]
hi, Philip, I got a fix for this, please review it.

**Comment by flihp** [comment]
done and done. Thanks @gwei3 !
