### ISSUE TITLE
resourcemgr uses 100% CPU on Ubuntu 16.04 x86_64

### ISSUE THREAD

**Issue by strongX509** [01org/TPM2.0-TSS#221]
I cloned the current TPM2.0-TSS master and built it on an Ubuntu 16.04 x86_64 desktop system. resourcemgr is started as a systemd service and doesn't use any CPU resources. After successfully executing any of the tpm2-tools (e.g. tpm2_listpcrs) the resourcemgr is left behind using up 100% of the CPU cycles. Repetitive tpm2-tool calls will cause the resourcemgr to use all available processor cores.

This behaviour does not occur with the official Ubuntu libtss2 package which apparently is based on a much older version of the TPM2.0-TSS software.

Best regards

Andreas

**Comment by strongX509** [comment]
Attached a backtrace of the thread caught in an endless loop: [resourcemgr_bt.txt](https://github.com/01org/TPM2.0-TSS/files/293706/resourcemgr_bt.txt)

**Comment by flihp** [comment]
Thanks for the backtrace @strongX509. Queuing this up.

**Comment by strongX509** [comment]
Thanks for the patch. resourcemgr is working fine now.
