### ISSUE TITLE
tpmtest failed TPM error: 0x9a2

### ISSUE THREAD

**Issue by DamienMolina** [01org/TPM2.0-TSS#233]
i have ubuntu 16.04 with TPM 2.0 (IFX SLB9665), have the latest version of TPM2.0-TSS, the resourcemgr daemon is running.
I run `test/tpmtest/tpmtest`, the first tests are OK, then I can run more specific tests:
```
Q - QUIT THE PROGRAM
D - PRINT DESCRIPTION ON ALL CASES
0 - RUN ALL TEST CASES
1 - GET/SET DECRYPT PARAM TESTS
2 - STARTUP TESTS
3 - CREATE, CREATE PRIMARY, and LOAD TESTS
5 - UNSEAL TEST
6 - TPM Version TESTS
7 - SELFTEST TESTS
8 - GET TEST RESULT TESTS
9 - DICTIONARY ATTACK LOCK RESET TEST
13 - GET_CAPABILITY TESTS
14 - PCR_EXTEND, PCR_EVENT, PCR_ALLOCATE, and PCR_READ TESTS
15 - HASH TESTS
16 - POLICY TESTS
20 - GET_RANDOM TESTS
21 - SHUTDOWN TESTS
24 - QUOTE CONTROL TESTS
25 - PCR ALLOCATE TEST
26 - RM TESTS
32 - EC Ephemeral TESTS
33 - SYMMETRIC ENCRYPT/DECRYPT TESTS
34 - ASYMMETRIC ENCRYPT/DECRYPT TESTS
35 - VERIFY SIGNATURE WITH EXTERNAL KEY TEST
36 - VERIFY SIGNATURE WITH CREATED KEY TEST
37 - NV EXTENSION TEST
38 - PCR EXTENDED TEST
39 - CLOCK/TIME TEST
```
Not all these tests are OK:
``` 
RUN ALL TEST CASES:

UNSEAL TEST  :
        passing case:   FAILED!  Resource Mgr Error: 0xc1000

		
POLICY TESTS:
Q - QUIT THIS TEST GROUP
D - PRINT DESCRIPTION ON ALL CASES IN THIS GROUP
0 - RUN ALL TEST CASES
Please select an action:0

RUN ALL TEST CASES:

POLICY TESTS:
Policy Test: PASSWORD
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   FAILED!  TPM Error: 0x9a2

TpmCmdServer died (TPM CMD), rval: 0x00000000, socket: 0xf.
OtherCmdServer died (Other CMD), socket: 0xe.


QUOTE CONTROL TESTS:
Q - QUIT THIS TEST GROUP
D - PRINT DESCRIPTION ON ALL CASES IN THIS GROUP
0 - RUN ALL TEST CASES
Please select an action:0

RUN ALL TEST CASES:

QUOTE CONTROL TESTS:
        passing case:   FAILED!  TPM Error: 0x184
PCR ALLOCATE TEST:
Q - QUIT THIS TEST GROUP
D - PRINT DESCRIPTION ON ALL CASES IN THIS GROUP
0 - RUN ALL TEST CASES
Please select an action:0

RUN ALL TEST CASES:

PCR ALLOCATE TEST  :
        passing case:   FAILED!  TPM Error: 0x9a2

RUN ALL TEST CASES:

RM TESTS:
Initializing Test RM Resource Manager Interface
socket created:  0x5
socket created:  0x6
Accept socket:  0xe
Resource Manager Other CMD Server accepted client
Client connected to server on port:  2324
Accept socket:  0xf
Resource Manager TPM CMD Server accepted client
Client connected to server on port:  2323
        failing case:   FAILED!  Ret code s/b: c2800, but was: c1000
TpmCmdServer died (TPM CMD), rval: 0x00000000, socket: 0x11.
OtherCmdServer died (Other CMD), socket: 0x10.

EC Ephemeral TESTS:
Q - QUIT THIS TEST GROUP
D - PRINT DESCRIPTION ON ALL CASES IN THIS GROUP
0 - RUN ALL TEST CASES
Please select an action:0

RUN ALL TEST CASES:

EC Ephemeral TESTS:
        failing case:   FAILED!  Ret code s/b: 8000b, but was: 143

RUN ALL TEST CASES:

SYMMETRIC ENCRYPT/DECRYPT & HASH TESTS:
        passing case:   PASSED!

New key successfully created (RSA 2048).  Handle: 0x80000009
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   FAILED!  TPM Error: 0x2c2

TpmCmdServer died (TPM CMD), rval: 0x00000000, socket: 0x11.
OtherCmdServer died (Other CMD), socket: 0x10.

RUN ALL TEST CASES:

ASYMMETRIC ENCRYPT/DECRYPT & HASH TESTS:
        passing case:   FAILED!  TPM Error: 0x9a2

		
		RUN ALL TEST CASES:

VERIFICATION on PUBLIC LOADED KEY TESTS:
        passing case:   FAILED!  TPM Error: 0x9a2

		
RUN ALL TEST CASES:

VERIFICATION on CREATED KEY TESTS:
        passing case:   FAILED!  TPM Error: 0x9a2

		RUN ALL TEST CASES:

NV EXTENSION TESTS:
        passing case:   PASSED!
        The count of defined NV Index: 4

        NV Index: 1800001

        NV Index: 1800003

        NV Index: 1c00002

        NV Index: 1c0000a
        passing case:   PASSED!
        passing case:   PASSED!
Name of loaded key: 00 04 aa 6f 4a 8b 97 3a f7 3f d7 b4 e4 a4 fa 56
6c 96 79 b9 5d c8
        passing case:   PASSED!

Loaded key handle:  80000007
        passing case:   FAILED!  TPM Error: 0x9a2
RUN ALL TEST CASES:

CLOCK/TIME TEST:
        passing case:   PASSED!

Current Time:110927392, Current Clock Info:678016494
        passing case:   FAILED!  TPM Error: 0x9a2


		
```

I often have the 0x9a2 error, as well as 0x2c2, 0x184, 0x921. Furthermore, if I run tpmclient: 
```
STARTUP TESTS:
        passing case:   PASSED!
        passing case:   FAILED!  TPM Error: 0x100

TpmCmdServer died (TPM CMD), rval: 0x00000000, socket: 0x6.
OtherCmdServer died (Other CMD), socket: 0x7.
```

So obviously, these errors have consequences on tpm2.0-tools(when I run `tpm2_takeownership -c`I have this 0x9a2 error.

**Comment by edonyM** [comment]
```sh
RUN ALL TEST CASES:

UNSEAL TEST  :
        passing case:   FAILED!  Resource Mgr Error: 0xc1000
```
According to this record, I think it might be you do not successfully run `resourcemgr`.

**Comment by DamienMolina** [comment]
Here is the result of resourcemgr
```
 resourcemgr&
[1] 19265
 Initializing device TCTI Interface
Initializing Resource Manager
maxActiveSessions = 64
gapMaxValue = 65535
socket created:  0x4
bind to IP address:port:  127.0.0.1:2324
Other CMD server listening to socket:  0x4
socket created:  0x5
bind to IP address:port:  127.0.0.1:2323
TPM CMD server listening to socket:  0x5
Starting SockServer (TPM CMD), socket: 0x5.
Starting SockServer (Other CMD), socket: 0x4.

```

Is there something wrong? Or do I have to check somewhere else to confirm I don't successfully run it?

**Comment by edonyM** [comment]
Mine is
```sh
Initializing device TCTI Interface
Resource Mgr, device TCTI, failed initialization: 0xa000a.  Exiting...
```
for I already have a resourcemgr running in background. Althoug I got the similar error, but it is not suitable for you. Sorry about that.

**Comment by DamienMolina** [comment]
```
~/TPM2.0-TSS# ps aux | grep resourcemgr
root     19265  0.0  0.0 170672  3056 ?        Sl   juin28   0:00 resourcemgr
~/TPM2.0-TSS# resourcemgr
Initializing device TCTI Interface
Resource Mgr, device TCTI, failed initialization: 0xa000a.  Exiting...
```
If the resourcemgr is already running, I have the same error.

I  have tried the tpm2.0-tools, with tpm2_takeownership -c
```
~/TPM2.0-TSS# ../tpm2.0-tools/src/tpm2_takeownership -c
Start to clear the Hierarchy auth....
ClearControl Failed ! ErrorCode: 0x9a2
```

What additional informations do you want? To install TPM2.0-TSS, i ran the following instructions:
```
git clone https://github.com/01org/TPM2.0-TSS.git
cd TPM2.0-TSS/
./bootstrap
./configure
make
make install
```

**Comment by edonyM** [comment]
Could you try this test? I am not sure if you change the policy so that authorize of PCR extend can not work.
```sh
25 - PCR ALLOCATE TEST
26 - RM TESTS
27 - NV INDEX PROTOTYPE TESTS
28 - DECRYPT/ENCRYPT SESSION TESTS
29 - SIMPLE HMAC SESSION TEST
30 - SIMPLE POLICY SESSION TEST
31 - CHANGE_PPS TESTS
32 - EC Ephemeral TESTS
33 - SYMMETRIC ENCRYPT/DECRYPT TESTS
34 - ASYMMETRIC ENCRYPT/DECRYPT TESTS
35 - VERIFY SIGNATURE WITH EXTERNAL KEY TEST
36 - VERIFY SIGNATURE WITH CREATED KEY TEST
37 - NV EXTENSION TEST
38 - PCR EXTENDED TEST
39 - CLOCK/TIME TEST
Please select an action:25

PCR ALLOCATE TEST:
Q - QUIT THIS TEST GROUP
D - PRINT DESCRIPTION ON ALL CASES IN THIS GROUP
0 - RUN ALL TEST CASES
Please select an action:D

PRINT DESCRIPTION ON ALL CASES IN THIS GROUP:
  PCR_Allocate Case(authHandle:0x4000000C,authArray:{1,{TPM_RS_PW}},pcrSelection:{count:0}):Passed
  PCR_Allocate Case(authHandle:0x4000000C,authArray:{1,{TPM_RS_PW}},pcrSelection:{count:1,{hash:TPM_ALG_SHA256,{160,0,0}}}):Passed

PCR ALLOCATE TEST:
Q - QUIT THIS TEST GROUP
D - PRINT DESCRIPTION ON ALL CASES IN THIS GROUP
0 - RUN ALL TEST CASES
Please select an action:0

RUN ALL TEST CASES:

PCR ALLOCATE TEST  :
	passing case:  	PASSED!
	passing case:  	PASSED!
```
And you can try `gdb tpm2_takeownership` to figure out which one lead to this error code. Mine works fine, I can not repeat your error. I just locate that the function `Tss2_Sys_ClearControl_Prepare` generate the error code `rval`.

**Comment by DamienMolina** [comment]
```
25 - PCR ALLOCATE TEST
26 - RM TESTS
32 - EC Ephemeral TESTS
33 - SYMMETRIC ENCRYPT/DECRYPT TESTS
34 - ASYMMETRIC ENCRYPT/DECRYPT TESTS
35 - VERIFY SIGNATURE WITH EXTERNAL KEY TEST
36 - VERIFY SIGNATURE WITH CREATED KEY TEST
37 - NV EXTENSION TEST
38 - PCR EXTENDED TEST
39 - CLOCK/TIME TEST
Please select an action:25

PCR ALLOCATE TEST:
Q - QUIT THIS TEST GROUP
D - PRINT DESCRIPTION ON ALL CASES IN THIS GROUP
0 - RUN ALL TEST CASES
Please select an action:d

PRINT DESCRIPTION ON ALL CASES IN THIS GROUP:
  PCR_Allocate Case(authHandle:0x4000000C,authArray:{1,{TPM_RS_PW}},pcrSelection:{count:0}):Passed
  PCR_Allocate Case(authHandle:0x4000000C,authArray:{1,{TPM_RS_PW}},pcrSelection:{count:1,{hash:TPM_ALG_SHA256,{160,0,0}}}):Passed

PCR ALLOCATE TEST:
Q - QUIT THIS TEST GROUP
D - PRINT DESCRIPTION ON ALL CASES IN THIS GROUP
0 - RUN ALL TEST CASES
Please select an action:0

RUN ALL TEST CASES:

PCR ALLOCATE TEST  :
        passing case:   FAILED!  TPM Error: 0x9a2
```

**Comment by DamienMolina** [comment]
It seems like my problem comes from the [CommonOneCall](https://github.com/01org/TPM2.0-TSS/blob/master/sysapi/sysapi_util/CommandUtil.c#L243) command. More precisely from the [FinishCommand](https://github.com/01org/TPM2.0-TSS/blob/master/sysapi/sysapi_util/CommandUtil.c#L80) and more precisely from this instruction : [Tss2_Sys_Execute](https://github.com/01org/TPM2.0-TSS/blob/master/sysapi/sysapi_util/CommandUtil.c#L92)

**Comment by flihp** [comment]
Hey @DamienMolina 

Looking at the last line here:
```
RUN ALL TEST CASES:

POLICY TESTS:
Policy Test: PASSWORD
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   FAILED!  TPM Error: 0x9a2

TpmCmdServer died (TPM CMD), rval: 0x00000000, socket: 0xf.
OtherCmdServer died (Other CMD), socket: 0xe.
```
It looks to me like the resourcemgr is dying on you? Can you repro again and check to see whether or not the resourcemgr is running immediately after this failure?

**Comment by DamienMolina** [comment]
It seems like the resourcemgr is still running after this failure.

```
POLICY TESTS:
Q - QUIT THIS TEST GROUP
D - PRINT DESCRIPTION ON ALL CASES IN THIS GROUP
0 - RUN ALL TEST CASES
Please select an action:d

PRINT DESCRIPTION ON ALL CASES IN THIS GROUP:
  PASSWORD:
        PolicyPassword Case:Passed
        PolicyGetDigest Case:Passed
        FlushContext Case:Passed
        EndAuthSession:Passed
        CreatePrimary Case:Passed
        Create Case:Passed
        Tss2_Sys_Load:Passed
        PolicyPassword Case:Passed
        PolicyGetDigest Case:Passed
        Tss2_Sys_Unseal:Failed(0x98E)
        Tss2_Sys_DictionaryAttackLockReset:Passed
        Tss2_Sys_Unseal:Passed
        Tss2_Sys_FlushContext:Passed
        Tss2_Sys_FlushContext:Passed
        EndAuthSession:Passed
  PASSWORD/PCR:
        Tss2_Sys_PolicyPassword:Passed
        Tss2_Sys_PCR_Read:Passed
        Tss2_Sys_PolicyPCR:Passed
        PolicyGetDigest Case:Passed
        FlushContext Case:Passed
        EndAuthSession:Passed
        CreatePrimary Case:Passed
        Create Case:Passed
        Tss2_Sys_Load:Passed
        Tss2_Sys_PolicyPassword:Passed
        Tss2_Sys_PCR_Read:Passed
        Tss2_Sys_PolicyPCR:Passed
        PolicyGetDigest Case:Passed
        Tss2_Sys_Unseal:Failed(0x98E)
        Tss2_Sys_DictionaryAttackLockReset:Passed
        Tss2_Sys_Unseal:Passed
        Tss2_Sys_FlushContext:Passed
        Tss2_Sys_FlushContext:Passed
        EndAuthSession:Passed
  AUTHVALUE:
        Tss2_Sys_PolicyAuthValue:Passed
        PolicyGetDigest Case:Passed
        FlushContext Case:Passed
        EndAuthSession:Passed
        CreatePrimary Case:Passed
        Create Case:Passed
        Tss2_Sys_Load:Passed
        Tss2_Sys_PolicyAuthValue:Passed
        PolicyGetDigest Case:Passed
        Tss2_Sys_Unseal:Failed(0x98E)
        Tss2_Sys_DictionaryAttackLockReset:Passed
        Tss2_Sys_Unseal_Prepare:Passed
        AddEntity:Passed
        ComputeCommandHmacs:Passed
        Tss2_Sys_Unseal:Passed
        DeleteEntity:Passed
        Tss2_Sys_FlushContext:Passed
        Tss2_Sys_FlushContext:Passed
        EndAuthSession

POLICY TESTS:
Q - QUIT THIS TEST GROUP
D - PRINT DESCRIPTION ON ALL CASES IN THIS GROUP
0 - RUN ALL TEST CASES
Please select an action:0

RUN ALL TEST CASES:

POLICY TESTS:
Policy Test: PASSWORD
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   PASSED!
        passing case:   FAILED!  TPM Error: 0x9a2

TpmCmdServer died (TPM CMD), rval: 0x00000000, socket: 0x8.
OtherCmdServer died (Other CMD), socket: 0xb.
root@tpm:~/TPM2.0-TSS# ps aux|grep resourcemgr
root      2750 19.9  0.0 203456  1012 pts/4    Sl   15:49   2:44 resourcemgr
```

**Comment by DamienMolina** [comment]
I forgot to mention, I try to make this TPM work on an Intel NUC5i3MYHE on Ubuntu 16.04.

**Comment by gwei3** [comment]
Some basic information: error code 0x9a2 means "TPM ERROR:  SESSION #1, TPM_RC_BAD_AUTH: authroization failure without DA implications".
So if you met any 0x9a2 error, usually it is due to that the platform auth is not NULL or owner auth is not NULL. tpmtest assume that the platform auth & owner auth are NULL before start running.

When you run with simulator, usually all the hierarchy auths are NULL. But when you run with physical TPM in production platforms, usually the bios will set a random value for platform auth, so all the tests requiring NULL platform auth can't be run with physical TPM in most platforms. I was trying to skip/hide those tests when aware of the Non-NULL platform auth.

As to Non-NULL owner auth, it is usually set by you when execute some standalone tools such as tpm2_takeownership etc. You need to clear the tpm.

There are some ways to clear the TPM:
1. when the platform auth is NULL, you can run tpm2_takeownership -c.
2. when the platform auth is non-NULL, you need to find out how to clear the tpm via bios settings, hardware jumper, etc.

I wish what I wrote above can help resolve some doubts.

**Comment by DamienMolina** [comment]
@gwei3 : you were right, on the Intel NUC5i3MYHE , there is a security jumper. It allows to clear Bios User and supervisor passwords, clear the TPM, etc...

So, if you have a Intel NUC5i3MYHE , open the NUC, pull out the jumper, and power on. You will boot on a Config Menu, press **[4]Clear Trusted Platform Module** , power off, and put the jumper back on. You can now boot and now, the TPM tests run, and the takeownership work.

**Comment by gwei3** [comment]
@DamienMolina : thank you for confirmation. Can I close this issue now?

**Comment by DamienMolina** [comment]
Yes you can close it.

**Comment by AshithPolepalli** [comment]
@DamienMolina faced similar issue but unable and follwed steps to clear TPM by removing jumper but still, unable to take ownership. below is the link mentioned regarding the issue
https://github.com/tpm2-software/tpm2-tools/issues/1137

I'm working on Nuc7i7BNH firmware TPM2.
Getting the following error on running command below, after performing following steps:

    TPM2 has been cleared by removing jumper and selecting option on boot.(as mentioned in NUC datasheet)

    $ tpm2_takeownership -o ownerpass -e endorsepass -l lockpass
    ERROR: Could not change hierarchy for Owner. TPM Error:0x9a2

couldn't understand what is the exact issue in setting password after clearing the TPM.

**Comment by zj1912** [comment]
I also met the 0x9a2 code when I am trying to test my TPM
# tpm2_createprimary -H o -g sm3_256 -G ecc -C primary.context
ObjectAttribute: 0x00030072
ERROR:
CreatePrimary Failed ! ErrorCode: 0x9a2

ERROR: Unable to run tpm2_createprimary






beforhand I have cleared the TPM on BIOS, and my tpm information is as follows:
# dmesg |grep -i tpm
[    0.000000] efi:  ACPI 2.0=0x8e23f000  ACPI=0x8e23f000  SMBIOS=0x8eb1d000  SMBIOS 3.0=0x8eb1c000  MEMATTR=0x88f60198  ESRT=0x85f96c18  TPMEventLog=0x55a38018
[    0.000000] ACPI: TPM2 0x000000008E283CD0 000034 (v04 LENOVO THINKSYS 00000100      01000013)
[    0.795191] tpm_tis NTN1004:00: 2.0 TPM (device-id 0x501, rev-id 24)

**Comment by zj1912** [comment]
I also met the 0x9a2 code when I am trying to test my TPM
# tpm2_createprimary -H o -g sm3_256 -G ecc -C primary.context
ObjectAttribute: 0x00030072
ERROR:
CreatePrimary Failed ! ErrorCode: 0x9a2

ERROR: Unable to run tpm2_createprimary






beforhand I have cleared the TPM on BIOS, and my tpm information is as follows:
# dmesg |grep -i tpm
[    0.000000] efi:  ACPI 2.0=0x8e23f000  ACPI=0x8e23f000  SMBIOS=0x8eb1d000  SMBIOS 3.0=0x8eb1c000  MEMATTR=0x88f60198  ESRT=0x85f96c18  TPMEventLog=0x55a38018
[    0.000000] ACPI: TPM2 0x000000008E283CD0 000034 (v04 LENOVO THINKSYS 00000100      01000013)
[    0.795191] tpm_tis NTN1004:00: 2.0 TPM (device-id 0x501, rev-id 24)

**Comment by zj1912** [comment]
**I also met the 0x9a2 code when I am trying to test my TPM**
# tpm2_createprimary -H o -g sm3_256 -G ecc -C primary.context
ObjectAttribute: 0x00030072
ERROR:
CreatePrimary Failed ! ErrorCode: 0x9a2

ERROR: Unable to run tpm2_createprimary






**beforhand I have cleared the TPM on BIOS, and my tpm information is as follows:**
# dmesg |grep -i tpm
[    0.000000] efi:  ACPI 2.0=0x8e23f000  ACPI=0x8e23f000  SMBIOS=0x8eb1d000  SMBIOS 3.0=0x8eb1c000  MEMATTR=0x88f60198  ESRT=0x85f96c18  TPMEventLog=0x55a38018
[    0.000000] ACPI: TPM2 0x000000008E283CD0 000034 (v04 LENOVO THINKSYS 00000100      01000013)
[    0.795191] tpm_tis NTN1004:00: 2.0 TPM (device-id 0x501, rev-id 24)

**Comment by zj1912** [comment]
**I also met the 0x9a2 code when I am trying to test my TPM**
# tpm2_createprimary -H o -g sm3_256 -G ecc -C primary.context
ObjectAttribute: 0x00030072
ERROR:
CreatePrimary Failed ! ErrorCode: 0x9a2

ERROR: Unable to run tpm2_createprimary






**beforhand I have cleared the TPM on BIOS, and my tpm information is as follows:**
# dmesg |grep -i tpm
[    0.000000] efi:  ACPI 2.0=0x8e23f000  ACPI=0x8e23f000  SMBIOS=0x8eb1d000  SMBIOS 3.0=0x8eb1c000  MEMATTR=0x88f60198  ESRT=0x85f96c18  TPMEventLog=0x55a38018
[    0.000000] ACPI: TPM2 0x000000008E283CD0 000034 (v04 LENOVO THINKSYS 00000100      01000013)
[    0.795191] tpm_tis NTN1004:00: 2.0 TPM (device-id 0x501, rev-id 24)

**Comment by zj1912** [comment]
**I also met the 0x9a2 code when I am trying to test my TPM**
# tpm2_createprimary -H o -g sm3_256 -G ecc -C primary.context
ObjectAttribute: 0x00030072
ERROR:
CreatePrimary Failed ! ErrorCode: 0x9a2

ERROR: Unable to run tpm2_createprimary






**beforhand I have cleared the TPM on BIOS, and my tpm information is as follows:**
# dmesg |grep -i tpm
[    0.000000] efi:  ACPI 2.0=0x8e23f000  ACPI=0x8e23f000  SMBIOS=0x8eb1d000  SMBIOS 3.0=0x8eb1c000  MEMATTR=0x88f60198  ESRT=0x85f96c18  TPMEventLog=0x55a38018
[    0.000000] ACPI: TPM2 0x000000008E283CD0 000034 (v04 LENOVO THINKSYS 00000100      01000013)
[    0.795191] tpm_tis NTN1004:00: 2.0 TPM (device-id 0x501, rev-id 24)

**Comment by zj1912** [comment]
**I also met the 0x9a2 code when I am trying to test my TPM**
# tpm2_createprimary -H o -g sm3_256 -G ecc -C primary.context
ObjectAttribute: 0x00030072
ERROR:
CreatePrimary Failed ! ErrorCode: 0x9a2

ERROR: Unable to run tpm2_createprimary






**beforhand I have cleared the TPM on BIOS, and my tpm information is as follows:**
# dmesg |grep -i tpm
[    0.000000] efi:  ACPI 2.0=0x8e23f000  ACPI=0x8e23f000  SMBIOS=0x8eb1d000  SMBIOS 3.0=0x8eb1c000  MEMATTR=0x88f60198  ESRT=0x85f96c18  TPMEventLog=0x55a38018
[    0.000000] ACPI: TPM2 0x000000008E283CD0 000034 (v04 LENOVO THINKSYS 00000100      01000013)
[    0.795191] tpm_tis NTN1004:00: 2.0 TPM (device-id 0x501, rev-id 24)
