### ISSUE TITLE
factor TCTI test code out of tpmclient

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#238]
These tests implement something similar to what other unit test frameworks call 'mocking'. There's no need to create our own version of this pattern when we already have cmocka available.

These tests should be factored out into their own unit tests that mock the system calls that we're causing to generate IO error by consciously passing them bad file descriptors.

**Comment by flihp** [comment]
Relevant code is currently here: https://github.com/01org/TPM2.0-TSS/blob/master/test/tpmclient/tpmclient.cpp#L623

**Comment by pdxjohnny** [comment]
I can't seem to find the TestTctiApis function that was around line 623 when this issue was created. Does this still need to be done?

**Comment by flihp** [comment]
Hey @pdxjohnny. I removed this earlier this month in e8f511f998d5c73a2fa228c25186c038e6fc0789 and forgot to close the issue before I went on vacation. Sorry for creating confusion here but I've been churning the test code a lot over the last few weeks.

**Comment by pdxjohnny** [comment]
@flihp hey thats great, I'm trying to get familiar with the code base so I was trying to make some things into tpmclient into unit tests. Sound like a good place to start?

**Comment by flihp** [comment]
Definitely a good idea @pdxjohnny. A word of caution though: the `tpmclient` code is quite brittle with several test cases creating side effects that future tests depend upon. I'm also sitting on a patch queue that makes a bunch of changes to fix issues in it that give coverity a panic attack so my apologies in advance if you end up having to rebase on account of this.

Other than these words of caution I say have at it! Also since there's basically 0 documentation for the test harness feel free to ask questions on the mailing list / IRC. I'll start paying more attention to these channels since it looks like there's a much appreciated up-tick in interest.

**Comment by pdxjohnny** [comment]
Great! Thanks man I'll keep all that in mind. :+1:
