### ISSUE TITLE
Install resourcemgr header

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#241]
This is needed by the tpm2_rc_decode utility for decoding errors from the resourcemgr: https://github.com/01org/tpm2.0-tools/issues/83

**Comment by flihp** [comment]
I'm killing this issue off. The resourcemgr will be removed as soon as I get the replacement through the Intel review process.

**Comment by williamcroberts** [comment]
Do we ever plan on being able to decode RM error codes?

Referencing: 01org/tpm2.0-tools#83

**Comment by flihp** [comment]
Yeah but the more I think about it the more I think the RC decoder ring should be a library, not a tool. The tool should just call a library to do the decoding. Probably worth creating a milestone for the work. This is the right repo for that library.
