### ISSUE TITLE
Is Tss2_Sys_GetCommandCode a SAPI function?

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#253]
I ran across this function in the code trying to figure out what the commandCodeSwapped field in the _TSS2_SYS_CONTEXT_BLOB structure is used for. It's only accessed in test code and this function that has a prototype similar to all of the other SAPI commands ... but it's no where in the spec (part 3).

Probably safe to just remove it?

**Comment by gwei3** [comment]
We should not remove Tss2_Sys_GetCommandCode. It was defined in sys api spec instead of tpm library spec part 3.

**Comment by flihp** [comment]
Thanks for the data @gwei3 but I can't see this function in the SAPI spec. There's a Tss2_Sys_GetContextSize function but not a Tss2_Sys_GetContext. Are you confusing the two or am I just unable to use ctrl+f properly? :smile:

**Comment by flihp** [comment]
Crap I got my functions messed up in that last comment. sry

**Comment by flihp** [comment]
Found it in the spec: section 8.7.4.1, my mistake.
