### ISSUE TITLE
Custom host to network byte order transforms?

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#254]
Was reading through the serialization logic and ran across the ChangeEndian\* / CHANGE_ENDIAN_\* function / macro pairs. These do a bunch of shifts to do a transform like htons / htonl. If using the hton\* functions is equivalent we should drop the extra code.

**Comment by flihp** [comment]
As always, not as simple as it should be: The change endian functions are non specific in the direction of the transform. Basically there's no way to know whether we're converting from host-to-network or the other way around (other than knowing what the code is doing). So this isn't a simple matter of find / replace.

So this will take some code reading. But by using these C functions it will make the code more readable by whoever comes along next.

**Comment by tstruk** [comment]
Fixed as part of #365
