### ISSUE TITLE
[question] No description or website provided

### ISSUE THREAD

**Issue by edonyM** [01org/TPM2.0-TSS#264]
I want to recommend this project to my friend. But I found there is no description or website provided. And I cannot find any project description in website https://01.org/. Can you tell me where I can found it?

**Comment by flihp** [comment]
Our README needs some love for sure. I've been meaning to spend some time on it for a while now but haven't made much progress. If you're willing to provide specifics about the information you're looking for I can prioritize that.

**Comment by edonyM** [comment]
Maybe something like http://ibmswtpm.sourceforge.net/ibmtss2.html can help. And some distinguishing feature description about this TSS implementation would better. BTW, thank you very much^~^

**Comment by flihp** [comment]
A "github page" seems to be the right way to do this. Probably best to have a public facing page that describes the architecture at a reasonable level of detail, then redirect to the github wiki for things like tested hardware / test configuration.

I'm gonna queue this up behind the current release planning. Will leave the issue open till I start making progress. Thanks.

**Comment by flihp** [comment]
I think we've got the description filled in, and a pretty OK README.md set up. We're not listed on 01.org but I've got no idea how to make this happen.
