### ISSUE TITLE
TPM2.0 Testing on Ubuntu with Intel's TPM2.0-TSS.

### ISSUE THREAD

**Issue by musakontron** [01org/TPM2.0-TSS#270]
Hi, we are using TPM2.0 (Fw 5.51.2098.2) on our platform:
, following is the error i am getting on our platform

$ ./test/tpmtest/tpmtest
we instantiate the tests suite and then a menu of desired test is displayed 
when it comes to 32 - EC Ephemeral TESTS we get this message:
**EC Ephemeral TESTS:
failing case: FAILED! Ret code s/b: 8000b, but was: 143
TpmCmdServer died (TPM CMD), rval: 0x00000000, socket: 0xa.
OtherCmdServer died (Other CMD), socket: 0xb.**

I made some research adn i found out https://github.com/01org/TPM2.0-TSS/issues/233 is describing the same issue.
Conclusion:
As to Non-NULL owner auth, it is usually set by you when execute some standalone tools such as tpm2_takeownership etc. You need to clear the tpm.
There are some ways to clear the TPM:
1. when the platform auth is NULL, you can run tpm2_takeownership -c.
2. when the platform auth is non-NULL, you need to find out how to clear the tpm via bios settings, hardware jumper, etc.
   i tried to clear it with the bios setup, i still have the failure.
   i tried to clear it using tpm.msc from windows but still the same failure.

At this point i tried:
/tpm2.0-tools/src/tpm2_takeownership -c
**Start to clear the Hierarchy auth....
ClearControl Failed ! ErrorCode: 0x9a2**

I disabled the option in BIOS setup (PH Randomization in TPM menu) and after that i was able to take ownership:
I performed  TPM Clear  from the BIOS and reboot the system.
When rebooting on OS (ubuntu), i reran 
root@ubuntu:~/TPM2.0-TSS# tpm2_takeownership -c
**Accept socket: 0x8
Resource Manager Other CMD Server accepted client
Accept socket: 0x9
Resource Manager TPM CMD Server accepted client

Start to clear the Hierarchy auth....
TpmCmdServer died (TPM CMD), rval: 0x00000000, socket: 0x9.
OtherCmdServer died (Other CMD), socket: 0x8.**

$ /usr/local/sbin/resourcemgr
$ ./test/tpmtest/tpmtest
we instantiate the tests suite and then a menu of desired test is displayed 
when it comes to 32 - EC Ephemeral TESTS we get this message:

**EC Ephemeral TESTS:
failing case: FAILED! Ret code s/b: 8000b, but was: 143
TpmCmdServer died (TPM CMD), rval: 0x00000000, socket: 0xa.
OtherCmdServer died (Other CMD), socket: 0xb.**

Can you help please ?

**Comment by musakontron** [comment]
fs1:\TPMUpdate> TPMFactoryUpd.efi -update tpm20-emptyplatformauth -firmware TPM20_5.51.2098.0_to_TPM20_5.60.2677.0.BIN ************************************************************** * Infineon Technologies AG TPMFactoryUpd Ver 01.00.1619.00 * **************************************************************
TPM update information:
       -----------------------
       Firmware valid                    :    Yes
       TPM family                        :    2.0
       TPM firmware version              :    5.51.2098.0
       Remaining updates                 :    64
       New firmware valid for TPM        :    Yes
       TPM family after update           :    2.0
       TPM firmware version after update :    5.60.2677.0
Preparation steps:
       TPM2.0 policy session created to authorize the update.
DO NOT TURN OFF OR SHUT DOWN THE SYSTEM DURING THE UPDATE PROCESS!
Updating the TPM firmware ...
       Completion: 100 %
       TPM Firmware Update completed successfully.

fs1:\TPMUpdate>
I updated it TPM2.0 to FW 5.60.
But we still have the failure

**Comment by flihp** [comment]
according to @DomiNic5787 this is caused by the TPM in question not supporting the algorithm / function under test. The RC from the dump above decodes (thanks to the tpm2_rc_decode tool from tpm2.0-tools) to "command code not supported". We've got a patch under review to update the `tpmtest` program to prevent unsupported commands from being executed.

**Comment by Nilesh-Deshmukh** [comment]
Hi,
where do find the TPMFactoryUpd.efi , Is it provided by Infineon?
If i install firmware will it clear TPM2?
