### ISSUE TITLE
RSA key generation exponent

### ISSUE THREAD

**Issue by YaHosoda** [01org/TPM2.0-TSS#274]
CreatePrimary/Create parameter

RSA key generation length=2048

Key Generation will fail
(rc=0x8d, value was out of allowed range)
if I set inPublic.t.publicArea.parameters.rsa.exponent other than 0.

Any information?

**Comment by flihp** [comment]
Do you have example code you're working from that we can use as reference. I've been ramping up on the serialization / marshaling logic and policy session mechanisms. I haven't got familiar with the key creation logic yet but this may be as good a time as any to do so. Still, getting some example code to help repo your issue will speed things up significantly.

**Comment by flihp** [comment]
Got no response to ask for more information, closing issue. If you want to fill in the details feel free to open this one back up.
