### ISSUE TITLE
convert cpp files to c

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#281]
A number of source files (specifically https://github.com/01org/TPM2.0-TSS/blob/master/tcti/tcti_socket.cpp) require the C++ compiler to build but they're not C++ source files. We need to get to the root cause of this. If we're using C++ for a reason then so be it but we shouldn't require users to install a C++ compiler just because we named the files wrong.

I thought there was already a ticket for this too but I can't seem to find it. If this is a duplicate please mark it as such with a link to the other lost issue.

**Comment by flihp** [comment]
Root cause of this was the Windows code. I guess it's easier to use windows C++ socket code than winsock directly. Platform specific code (windows vs linux) should be factored out into separate files so the vestiges of windows support in the socket TCTI don't drag down progress on the Linux stuff.

**Comment by williamcroberts** [comment]
This can be closed...

**Comment by williamcroberts** [comment]
Whoops wrong project 👎

**Comment by flihp** [comment]
resolved in #339
