### ISSUE TITLE
resource manager eats up more that 100% CPU if client disconnects without freeing resources

### ISSUE THREAD

**Issue by dguerri** [01org/TPM2.0-TSS#286]
Steps to reproduce:
 - run a lengthy operation using TPM tools (e.g. `tpm2_listpcrs`);
 - CTRL-c the application (timing is important as this should be issued after connection to the TPM is opened and before it is closed by the app);
 - observe resource manager eating up more than 100% and sockets staying in CLOSE_WAIT state forever;

```
root@ubuntu:~# ps -p 88331 -o %cpu,%mem,cmd
%CPU %MEM CMD
 176  0.0 resourcemgr -sim
```
and 
```
root@ubuntu:~# lsof -Pani -p 88331
COMMAND     PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
resourcem 88331 dguerri    3u  IPv4 475745      0t0  TCP 127.0.0.1:52162->127.0.0.1:2322 (ESTABLISHED)
resourcem 88331 dguerri    4u  IPv4 475746      0t0  TCP 127.0.0.1:57148->127.0.0.1:2321 (ESTABLISHED)
resourcem 88331 dguerri    5u  IPv4 475747      0t0  TCP 127.0.0.1:2324 (LISTEN)
resourcem 88331 dguerri    6u  IPv4 475748      0t0  TCP 127.0.0.1:2323 (LISTEN)
resourcem 88331 dguerri    9u  IPv4 476814      0t0  TCP 127.0.0.1:2324->127.0.0.1:35818 (CLOSE_WAIT)
```

As it turns out, the resource manager doesn't close the socket when it receives 0 from recv.
From `man recv`:

```
Return Value

These calls return the number of bytes received, or -1 if an error occurred. 
The return value will be 0 when the peer has performed an orderly shutdown.
```

Instead of detecting that the client has closed the connection, `resoucemgr` keeps calling recv in an infinite for loop (see [common/sockets.cpp](https://github.com/01org/TPM2.0-TSS/blob/master/common/sockets.cpp#L22-L27))

**Comment by gwei3** [comment]
good finding and fix! I got similar complain from some other guys about similar issues. Thanks for dig it out. @flihp please review and merge it for 1.0 release. It is a critical bug.

**Comment by dguerri** [comment]
Thanks and you are welcome!
I was thinking that maybe a cleaner fix would use a special exit code from the recv loop and then we could exit from the main loop as it was a clean exit?
