### ISSUE TITLE
UNSEAL test always fail with error code 0x101

### ISSUE THREAD

**Issue by yunyings** [01org/TPM2.0-TSS#290]
When runs ./test/tpmtest/tpmtest for automatic full test on x86_64, it always fails at UNSEAL test with error code 0x101:
_UNSEAL TEST  :
               passing case:      FAILED!  TPM Error: 0x101_

Test log is attached.

I'm testing with RHEL 7.3, kernel version 3.10.0-481.el7.x86_64.
I tried TPM2.0-TSS with both tag 1.0-beta_1 and latest code base today(Oct 17, 2016), same error.

Same issue found with latest SUSE release - SLES12 sp2.

[tpm_failure_UNSEAL_0x101.txt](https://github.com/01org/TPM2.0-TSS/files/532641/tpm_failure_UNSEAL_0x101.txt)

**Comment by yunyings** [comment]
Retested with latest release - v1.0, tpmtest still fails at UNSEAL Test with same TPM error code 0x101.
See attached log for details.
[TSS2_v1_0_tpmtest_failure.txt](https://github.com/01org/TPM2.0-TSS/files/596584/TSS2_v1_0_tpmtest_failure.txt)

**Comment by yunyings** [comment]
Tested on NUC with Wind River Linux 9(pre-GA release, using kernel 4.8), tpmtest fails at same place:
UNSEAL TEST  :
        passing case:   FAILED!  TPM Error: 0x101

Attached has more details.
[TPM_WRL9_RCPL0_20161215_NUC.txt](https://github.com/01org/TPM2.0-TSS/files/656621/TPM_WRL9_RCPL0_20161215_NUC.txt)

**Comment by yunyings** [comment]
Jimmy/Philip, please check whether it's a bug in this tool. Thanks.

**Comment by flihp** [comment]
Doing a quick lookup on that error code indicates that it's reporting an internal TPM failure. Any chance your platform has an update you having applied?

**Comment by yunyings** [comment]
Philip, what does "an internal TPM failure" means? I have not done any update to the NUC. The NUC has an discrete IFX TPM2.0 module, which I don't even know how to update. Anything else I could check for your analysis input?

**Comment by flihp** [comment]
This issue is very stale and looks to be relevant to a quirk in a TPM2 device, not the software here. Please re-open if you still require help with this issue or track me down directly.
