### ISSUE TITLE
compiling with std=c99 causes inclusion failure

### ISSUE THREAD

**Issue by williamcroberts** [01org/TPM2.0-TSS#305]
Building tpm2.0-tools with CFLAGS=-std=c99 causes:

In file included from /usr/local/include/sapi/tpm20.h:46:0,
                 from src/debug.c:31:
/usr/local/include/sapi/tss2_tcti.h:66:2: error: #error Info: Platform not supported for TCTI_POLL_HANDLES
 #error Info: Platform not supported for TCTI_POLL_HANDLES

It appears as though the if defined linux || defined unix is not working. Testing locally seems to indicate that __linux__ should be used instead, or included in the ifdef switch.

**Comment by flihp** [comment]
The logic there is a little weird. Not sure why we define that type for the `TCTI_POLL_HANDLES` stuff at all there if we're just going to `#error` out. I guess that's a separate issue all together though. Back to your point:

`linux` is an obsolete symbol (not POSIX) for Linux systems. It should be `__linux__`. Similarly `unix` should be `__unix__`. Our use of `__linux` is equally broken. https://sourceforge.net/p/predef/wiki/OperatingSystems/

I spent a few minutes with this and the `__linux__` stuff is pretty easy to fix. Other stuff goes sideways with `<time.h>` stuff in `criticalsection.h`.

**Comment by flihp** [comment]
Looks like  gcc compiles with `-std=gnu89` by default, might be better to go to `-std=gnu99` instead of straight to `-std=c99`. This stuff won't compile with `-std=c89` after all.

**Comment by williamcroberts** [comment]
Yeah I figured we could flip this later if we want. The C build for tpm2.0-tools was the one htting this #define include issue when I was flipping that over.

**Comment by flihp** [comment]
Gotcha. I've already started playing around with this so I figure cleaning it up a bit is a good idea since I'm already halfway there. I'll update the default CONFIG_SITE file to include `-std=gnu99` and fix up the `__linux/linux` to `__linux__`.

Do you have an opinion on `ifdef __blah__` vs `if defined(__blah__)`?

**Comment by flihp** [comment]
I guess '#ifdef' is limited to a single conditional (can't append logical operators) so maybe it's best to go with `#if defined` so we can handle the logical or.

**Comment by williamcroberts** [comment]
Yeah ifdef as you pointed out is limited, so for compound statements #if defined() is the choice.

**Comment by flihp** [comment]
@williamcroberts : got a PR over in #310

**Comment by flihp** [comment]
Looks like the gnu99 stuff merged in #310 was sufficient to address this. If no feel free to reopen this issue.
