### ISSUE TITLE
tpmClient fails with Microsoft TPM simulator

### ISSUE THREAD

**Issue by danglus** [01org/TPM2.0-TSS#308]
Hi,
  For some reason, tpmClient tests are all working with the ibm simulator (https://sourceforge.net/projects/ibmswtpm2/?source=typ_redirect), but when I try to run it with Microsoft simulator (https://www.microsoft.com/en-us/download/details.aspx?id=52507) it fails with the following error message:
"
 CREATE PRIMARY, encrypt and decrypt TESTS:
	failing case: 	PASSED!
	passing case:  	PASSED!

New key successfully created in owner hierarchy (RSA 2048).  Handle: 0x80000003
Name of created primary key: 00 04 23 5b 7a 2c 64 92 bb 98 66 ff 6b 95 ba 0b 
90 42 a9 91 86 49 
	failing case: 	FAILED!  Ret code s/b: 18b, but was: 98b
"
(I had the TPM2.0-TSS compiled on Ubunbu running in VirtualBox , and the simulator running on Windows).

seems like the problem is the encrypt command itself (in line 7113(

    rval = Tss2_Sys_RSA_Encrypt(sysContext, keyHandle, &sessionsData, &message, &inScheme, &outsideInfo, &outData, &sessionsDataOut);
    if( tpmSpecVersion >= 124 )
        CheckFailed( rval, TPM_RC_S + TPM_RC_1 + TPM_RC_HANDLE );
    else
        CheckFailed( rval, TPM_RC_1 + TPM_RC_HANDLE );

what do you think? is that a problem with the MSFT simulator?

**Comment by flihp** [comment]
I doubt it's a problem with the simulator. More likely a version thing. Currently we're testing against the 532 version of the IBM simulator: https://github.com/01org/TPM2.0-TSS/blob/master/script/simulator.inc#L3 There's been a newer version released however and likely this is updated for a newer release of the TPM spec.

This may be related to the issue raised by @wcarthur1 over on #285?

**Comment by danglus** [comment]
The simulator returns "TPM spec version: 121"
  but the return code of 0x98B (TPM_RC_S + TPM_RC_1 + TPM_RC_HANDLE)

**Comment by flihp** [comment]
I'll work on a repro when I get back to a Windows system. Probably best to work on breaking this specific test out into the new integration test framework we've been working on at the same time.

**Comment by danglus** [comment]
Hi,
  The application that I need will have its own dedicated server, hence, working directly with the driver is fine. We know that the resourcemgr is not in a good shape, so I think that I can close this ticket.
Thanks!
Dan
