### ISSUE TITLE
CommandUtil.c

### ISSUE THREAD

**Issue by williamcroberts** [01org/TPM2.0-TSS#309]
rval == TSS2_RC_SUCCESS always TRUE. The last branch in the snippet below checks that rval is is OK, however, that is initialized to OK and not changed since function entry. Thus that branch is always taken. Should it be chcking the SYS_CONTEXT->rval value instead?

`
TSS2_RC     rval = TSS2_RC_SUCCESS;
UINT32      responseSize;

if( SYS_CONTEXT->rval != TSS2_RC_SUCCESS )
    return SYS_CONTEXT->rval;
if( cmdAuthsArray != 0 )
{
    SYS_CONTEXT->rval = Tss2_Sys_SetCmdAuths( sysContext, cmdAuthsArray );
}

if( rval == TSS2_RC_SUCCESS )
{
    SYS_CONTEXT->rval = FinishCommand( SYS_CONTEXT, cmdAuthsArray, &responseSize );
`

**Comment by flihp** [comment]
Yeah the outer conditional @ https://github.com/01org/TPM2.0-TSS/blob/master/sysapi/sysapi_util/CommandUtil.c#L241 looks like a n00p to me too. Looks like it should be
```
SYS_CONTEXT-rval
```
instead as you note.
