### ISSUE TITLE
sockets.cpp doesn't play well with UNIX signals

### ISSUE THREAD

**Issue by dguerri** [01org/TPM2.0-TSS#319]
I wrote an app using TPM2.0-TSS sysapi and I am defining an handler for SIGUSR1
As it turns out, `send` and `recv` syscalls in `sockets.cpp` get interrupted by signals but `sockets.cpp` doesn't check the errno value.
As a result, my app crashes.

**Comment by flihp** [comment]
The sockets module needs lots of love. Great fix over in #320 @dguerri
