### ISSUE TITLE
Systemd service for resourcemgr

### ISSUE THREAD

**Issue by kgizdov** [01org/TPM2.0-TSS#321]
Hi,

Can we get a systemd service for starting resourcemgr on boot or otherwise?

Currently, the whole procedure of starting resourcemgr and then running commands seems very manual and not really optimal.

I was thinking something along the lines of:
```sh
$ cat /usr/lib/systemd/system/tpm2_resourcemgr.service
[Unit]
Description=Manager for Trusted Computing Module 2.0
After=sysinit.target

[Service]
ExecStart=/usr/bin/resourcemgr

[Install]
WantedBy=default.target
```

**Comment by flihp** [comment]
I don't know much about systemd but I hacked up an example service file a while back and stashed it in `contrib/`. Did this one not work for you? https://github.com/01org/TPM2.0-TSS/blob/master/contrib/resourcemgr.service

**Comment by kgizdov** [comment]
I have a couple of questions/issues about the service file you linked.

1. Why is the service setting STDOUT to null? Systemd is quite capable of handling logs and that seems like a non-standard edit. What's the reasoning behind this?

2. Do we have to run the service as a specific user? I initially tried running as a user, but the service kept failing. Does it need to be specifically the 'tss' user?

3. ExecStart directive seems to ignore user-specific install path. Could we have the script be edited during configure/install step so that the proper path/prefix is respected? This is specifically related to packaging, so I don't know if it will remain relevant during future development.

**Comment by flihp** [comment]
1. No clue. This was based on a template that I grabbed from somewhere and it "worked" so I used it.
1. Most distros ship a udev rule that causes `/dev/tpm0` to be owned by a user and group called `tss`. I've got a udev rule in the source tree that does this as well.
1. Would gladly take a patch for this.

**Comment by kgizdov** [comment]
I've been trying to patch this and make a pull request, but frankly I am new to the GNU Autoconf tools. I am struggling to define a rule which results in adding a `configure` option to use the `--prefix`. I can however easily create a rule inside the configure script after it's been generated. But that's obviously not the way to go. As I imagine it a simple:
```Makefile
.PHONY: systemd
systemd:
    @sed -i "s/\/usr\/local/${prefix}/' ${path_to_systemd.service_in_src}
``` 
would do, where `systemd` is a requirement of the build. Or if we want to be even better, we first patch the service file:
```bash
...
[Service]
ExecStart=__PREFIX__/sbin/resourcemgr
...
```
and then the rule will be:
```Makefile
.PHONY: systemd
systemd:
    @sed -i "s/__PREFIX__/${prefix}/' ${path_to_systemd.service_in_src}
```
I realise that this needs `sed`, which is not part of Autoconf tools, but at least it's GNU. Not sure what the respective Autoconf tool is.

**Comment by edonyM** [comment]
I have an other idea about resourcemgr, it can be re-writed as a daemon. When the first tpm2_xxx command executed, the command initiate resourcemgr daemon. There is no need to use systemd service. ;)

**Comment by flihp** [comment]
@kgizdov: Looks like you're on the right path: keep things simple. Take a look at what I did for the man page generation in the tpm2.0-tools project: https://github.com/01org/tpm2.0-tools/blob/master/Makefile.am#L224

I'd prefer that the service file not be built / installed by default since this implicitly makes systemd a dependency. A simple build rule to generate the service file from a template makes the most sense.

In these situations looking for "prior art" is usually a good idea. Take a look at the daemon(7) man page. It has a few different strategies that you may find helpful.

**Comment by kgizdov** [comment]
well, the systemd does need to be a dependency if `configure --with-systemd` is a thing. This way, we can have an automatic systemd service file or not, just by specifying the option. How does that sound?

**Comment by kgizdov** [comment]
As I said, not sure what I am doing with Autoconf tools, but something like this:
```
AC_ARG_ENABLE([systemd],
            [AS_HELP_STRING([--with-systemd],
                            [configure with systemd service file(default is no)])],
            [enable_systemd=$enableval],
            [enable_sytemd=no])
```
or something?

**Comment by flihp** [comment]
Yeah that looks good. You can combine this with AM_CONDITIONAL to selectively build / install stuff in Makefile.am

**Comment by flihp** [comment]
resourcemgr was just removed, replacement is here: http://github.com/01org/tpm2-abrmd. It has a service file that's built / installed by default. Some configurability like what's discussed here would be welcome.

**Comment by kgizdov** [comment]
I was just thinking to start doing something for this as I did not have any time recently. But I will try and make something soon.
