### ISSUE TITLE
CHANGE_ENDIAN_* usage in sapi_util functions

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#365]
These ones are a bit more complex.

sysapi/sysapi_util/Marshal_TPM2B_ECC_POINT.c
sysapi/sysapi_util/unmarshal_simple_tpm2b.c
sysapi/sysapi_util/CopySessionData.c
sysapi/sysapi_util/Marshal_TPM2B_SENSITIVE.c
sysapi/sysapi_util/unmarshal_simple_tpm2b_no_size_check.c
sysapi/sysapi_util/Marshal_TPM2B_PUBLIC.c
sysapi/sysapi_util/Marshal_TPM2B_SENSITIVE_CREATE.c

**Comment by tstruk** [comment]
Fixed in 16369f8c
