### ISSUE TITLE
put source code of tpm simulator into test suite would be better

### ISSUE THREAD

**Issue by edonyM** [01org/TPM2.0-TSS#376]
If workspace got network problem, `make simulator-build` would not work and the same with `make check`. So copy the `ibmtpm532.tar` into `TPM2.0-TSS/test/ibmtpm532/` and do some modification of Makefile.am, it would be better.
> Makefile.am patch
```patch
--- TPM2.0-TSS-master/Makefile.am       2017-03-13 10:05:00.000000000 +0800
+++ TPM2.0-TSS/Makefile.am      2017-03-13 16:26:15.829007049 +0800
@@ -195,6 +195,8 @@
        cp $< $@
        chmod 755 $@
 simulator-build : test/simulator-build.sh test/simulator.inc
+       mkdir test/ibmtpm532
+       cp $(srcdir)/test/ibmtpm532.tar test/ibmtpm532/
        test/simulator-build.sh
 test/simulator-run.sh : $(srcdir)/script/simulator-run.sh
        cp $< $@
```

**Comment by flihp** [comment]
I'm with you in that running `make check` requires a network connection. I'm not quite sure what your patch is doing though. What's your desired end behavior? It sounds to me like you want to be able to provide a local simulator tarball into the simulator-build target but I'm not sure.

**Comment by edonyM** [comment]
@flihp sorry to make you confused, The workflow is `make` --> `make simulator-build` --> `make simulator-start` --> `make check`. And the network connection only works to get simulator tarball from sourceforge so that `make simulator-build` can work. Is that right? 
So, if I download the `ibmtpm532.tar` beforehand and put it into source file directory, for instance directory `test`, and modify the `Makefile.am` as the patch file shown before. The workflow worked perfectly when I checked my method.

**Comment by flihp** [comment]
No worries. I see where you're going with this and I like the feature. I'd summarize it as being able to support "off-line" testing. This would mean allowing for a mechanism to provide an alternative location for the simulator tarball.

Your approach is super simple (which is great) but it requires the user know a magic location to place the simulator tarball as a way to by-pass the download. I'd be happier with an approach that was more explicit. Something like an environment variable we can pass to `make` that has the URL for the simulator tarball (which could be a local file:// URL). Something that would look like:
```
$ SIM_TARBALL=./simulator-mirror.tar.gz make simulator-build
```
This would be something that could be put into a CONFIG_SITE file to make life even easier. Not sure how this would effect the script that does the download / build though so it may be a bit of work.

What do you think?

**Comment by edonyM** [comment]
Yeah, agree with you. My approach is not good enough.
Actually, to implement this "off-line" testing, I think we should do some boundary definition,
1. the TPM simulator works for test purpose, so source code of simulator tarball belong to test suite module
2. according to the first definition, we'd better put the simulator tarball into `test` directory
---
Based on the above, here is my improvement, and it was tested OK.
#### 1. `test` directory structure
```sh
./TPM2.0-TSS/test
├── common
│   └── sample
├── ibmtpm532
│   └── ibmtpm532.tar
├── integration
│   ├── asymmetric-encrypt-decrypt.c
│   ├── context-util.c
│   ├── context-util.h
│   ├── get-random.c
│   ├── log.h
│   ├── main.c
│   ├── pcr-extension.c
│   ├── self-test.c
│   ├── test.h
│   ├── test-options.c
│   └── test-options.h
├── tpmclient
│   ├── good
│   ├── tpmclient.c
│   └── tpmclient.h
├── tpmtest
│   └── tpmtest.c
└── unit
    ├── CommonPreparePrologue.c
    ├── CopyCommandHeader.c
    ├── getcommands-malloc-mock.c
    ├── GetNumHandles.c
    ├── marshal-TPM2B-simple.c
    ├── tcti-device.c
    ├── UINT16-marshal.c
    ├── UINT32-marshal.c
    ├── UINT64-marshal.c
    └── UINT8-marshal.c

8 directories, 25 files
```
#### 2. modification
```patch
diff -uNr TPM2.0-TSS-master/Makefile.am TPM2.0-TSS-offline/Makefile.am
--- TPM2.0-TSS-master/Makefile.am	2017-03-16 09:00:26.000000000 +0800
+++ TPM2.0-TSS-offline/Makefile.am	2017-03-17 22:51:59.664915185 +0800
@@ -202,7 +202,9 @@
 test/simulator-build.sh : $(srcdir)/script/simulator-build.sh
 	cp $< $@
 	chmod 755 $@
-simulator-build : test/simulator-build.sh test/simulator.inc
+test/ibmtpm532.tar: $(srcdir)/test/ibmtpm532/ibmtpm532.tar
+	cp $< $@
+simulator-build : test/simulator-build.sh test/simulator.inc test/ibmtpm532.tar
 	test/simulator-build.sh
 test/simulator-run.sh : $(srcdir)/script/simulator-run.sh
 	cp $< $@
diff -uNr TPM2.0-TSS-master/script/simulator-build.sh TPM2.0-TSS-offline/script/simulator-build.sh
--- TPM2.0-TSS-master/script/simulator-build.sh	2017-03-16 09:00:26.000000000 +0800
+++ TPM2.0-TSS-offline/script/simulator-build.sh	2017-03-17 22:52:20.615912862 +0800
@@ -15,6 +15,9 @@
 if [ ! -d ${SIM_DIR} ]; then
     mkdir ${SIM_DIR};
 fi
+if [ -f ${TEST_DIR}/${SIM_FILE} ]; then
+    mv ${TEST_DIR}/${SIM_FILE} ${SIM_DIR}
+fi
 cd "${SIM_DIR}"
 if [ ! -f ${SIM_FILE} ]; then
     wget ${SIM_URL} || { echo "failed to wget ${SIM_URL}"; exit 1; }

```

**P.S.**
If you agree with my idea, may I do some pull request about this?

**Comment by flihp** [comment]
Sorry for losing track of this @edonyM. If I'm reading this patch right it looks like you want to include the simulator tarball in the git repo. I'm not sure I can get behind that. It's a pretty big blob but not too big to download. Like I say above, for users that can't download the tarball in their build system we can provide a simple environment variable to allow them to provide the tarball that they've obtained through some other mechanism.

**Comment by flihp** [comment]
This went stale a while back but I've been hard at work polishing up the integration test harness. This work is mostly concluded by the integration of the `tpmclient` executable into the itnegration test harness. As part of this I've removed the simulator-* make targets. These seemed like a good idea at the time but I never managed to get them working the way that I wanted and they often resulted in downloading the simulator source code and building it multiple times as part of my workflow (the subject of this thread).

These make targets have now been replaced by an option to the configure script that tells the build system where to find a pre-built version of the simulator. This is infinitely more flexible and gets rid of all of the issues with the simulator-* make targets.

As such I'm closing this issue but if you run into any issues with the new integration test stuff feel free to create a new issue.
