### ISSUE TITLE
Different behavior on TPM 2.0 devices if sensitiveDataOrigin == 1 when issuing tpm2_create command

### ISSUE THREAD

**Issue by jiazhang0** [01org/TPM2.0-TSS#390]
Hi,

I'm not sure whether this is the right place to report this issue. But I think the expert here may give some useful hints.

> [ Quoting: Trusted Platform Module Library Part 1: Architecture ]
> 25.2.3 sensitiveDataOrigin
When a symmetric object (TPM_ALG_KEYEDHASH or TPM_ALG_SYM) is created, the caller may
provide the secret data or have the TPM generate it. If the TPM is to be the source of the data, then the
caller will SET this attribute. Otherwise, this attribute will be CLEAR and the caller-provided data will be
used.
> [ End of Quote ]

However, in Trusted Platform Module Library Part 4 Supporting Routines Section 7.6.3.3, the reference implementation has a different behavior when the data source is set to TPM (sensitiveDataOrigin == 1):

>     switch(publicArea->type)
>         {
>           case TPM_ALG_KEYEDHASH:
>             // if this is a data object (sign == decrypt == CLEAR) then the
>             // TPM cannot be the data source.
>             if(!attributes.sign && !attributes.decrypt
>                && attributes.sensitiveDataOrigin)
>                 result = TPM_RC_ATTRIBUTES;
>

This reference code is retrieved from ibmswtpm2.

According to my testing, sensitiveDataOrigin == 1 with sign == 0 and decrypt == 0 is working with dTPM such as Infineon TPM SLB 9665 and STMicroelectronics ST33TPHF2ESPI, and fails with Intel fTPM and ibmswtpm2. I have a tpm2 app based on TPM2.0-TSS and validated on above devices.

Do you think this is the conflict in the spec? Is there necessary add such a check in TPM2.0-TSS?

**Comment by idesai** [comment]
sensitiveDataOrigin being set, guarantees the object being created has an entropy that came from within the TPM trust boundary. If you unseal this object and bring the data in clear, one could essentially create object with identical sensitive data but with sensitiveDataOrigin clear.
Unlike sealed data objects, this attribute is useful for creating keys whose private portion never leaves the TPM boundary and so TCG brought in this change.
For reference look at the notes in section 8.3.5.5 Part 2 of the specification.

**Comment by idesai** [comment]
Additionally, if entropy and authorization are the driving needs for sealing the object, you can create a key (with entropy and authorization guarantees from within TPM trust boundary) and encrypt/decrypt a zero buffer with the key and use that data instead of sealing/ unsealing object.

**Comment by jiazhang0** [comment]
Hi Idesai,

Thanks for your comments. In addition, I find out the evidence, quoted from Page 46 of TPM-Rev-2.0-Part-3-Commands-01.38:

c) If the Object is a keyedHash object:
1) If inSensitive.sensitive.data is an Empty Buffer, and both sign and decrypt are CLEAR in the attributes of inPublic, the TPM shall return TPM_RC_ATTRIBUTES. This would be a data object with no data.

This description matches up the reference code. Therefore, I think Intel fTPM and ibmswtpm2 correctly implement the spec but the dTPM devices such as Infineon TPM SLB 9665 and STMicroelectronics ST33TPHF2ESPI don't.
