### ISSUE TITLE
Sample code for working directly with /dev/tpm0

### ISSUE THREAD

**Issue by danglus** [01org/TPM2.0-TSS#391]
Hi,
  Can I find somewhere sample code for working directly with a TPM? that is without the resourcemgr?
I'm looking for minimal code (something simpler than tpm2_tools).

Dan

**Comment by webmeister** [comment]
How low-level do you want to work? This is how you can execute a TPM2_GetTestResult with Python:

```
import binascii

with open('/dev/tpm0', 'r+b', buffering=0) as tpm:
	tpm.write(binascii.unhexlify(b'80010000000a0000017c'))
	print(tpm.read())
```

**Comment by danglus** [comment]
The same level as the tpm2_tools use, I want to use the TSS functions and data-structures, I think that it is the SAPI layer.

This diagram, found in  TSS_system_API-01 seems to be relevant:
[cid:image001.png@01D2A897.A2AA17F0]

**Comment by DommiB** [comment]
Did you see the (very basic) programs under TPM2.0-TSS/test/integration ? You can change the define TCTI_DEFAULT (in test_options.h) to DEVICE_TCTI. Then the application will work directly with the device.  

Cheers

**Comment by danglus** [comment]
OK, 
  I managed to create a simple stand-alone code that can interact directly with the TPM. The attached program use the Tss2_Sys_GetRandom() command to get a random number from the TPM.

[get_random.c.txt](https://github.com/01org/TPM2.0-TSS/files/900682/get_random.c.txt)

  I'm currently working on additional samples that can do more staff.

 Cheers!
Dan

**Comment by furtnerthomas** [comment]
Hi,
the [Infineon Embedded Linux TPM Toolbox 2 (ELTT2) for TPM 2.0](https://github.com/Infineon/eltt2) can be used to get started with the TPM. You can e.g. request a random number from the TPM 2.0.

**Comment by WolsYang** [comment]
Hi @webmeister 
I am try to get tpm VID from /dev/tpm0
> 80010000000a0000017c
May I know where is this nuber from?

**Comment by webmeister** [comment]
>  I am try to get tpm VID from /dev/tpm0

The VID, i.e. the contents of the TPM_DID_VID register defined in [TIS](https://trustedcomputinggroup.org/resource/pc-client-work-group-pc-client-specific-tpm-interface-specification-tis/)? As far as I know, there is no way for user space to directly access TIS registers via /dev/tpm0. But you can probably get equivalent information by requesting TPM_PT_MANUFACTURER with TPM2_GetCapability.

>  May I know where is this nuber from?

This is what you get when you look into the [TPM 2.0 Library specification](https://trustedcomputinggroup.org/resource/tpm-library-specification/). In this case, Table 13 "TPM2_GetTestResult Command" in "Part 3: Commands" will tell you that TPM2_GetTestResult consists of three parts (tag, commandSize, commandCode) and you can use "Part 2: Structures" to look up the actual byte values of TPM_ST_NO_SESSIONS (8001), TPM_CC_GetTestResult (0000017c), etc.

**Comment by webmeister** [comment]
> I'm confused why command size is 10(0x0000000a)

80010000000a0000017c is a hex representation of ten bytes (two bytes tag, four bytes commandSize, four bytes commandCode), hence commandSize is 10.
