### ISSUE TITLE
TCTI overview docs

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#398]
The wiki needs a page giving an overview of what a TCTI is, what it does and how to user one.

**Comment by danglus** [comment]
The TSS spec doc includes a good overview:
https://trustedcomputinggroup.org/tss-system-level-api-tpm-command-transmission-interface-specification/

**Comment by flihp** [comment]
Been slow going on the TSS with efforts to get the tpm2-abrmd out the door in full swing. Lost track of this for a bit. See PR #421 for the proposed solution.
