### ISSUE TITLE
Add option to allow transient object handle to be used across connections in resourcemgr

### ISSUE THREAD

**Issue by gwei3** [01org/TPM2.0-TSS#40]
In current resourcemgr, transient virtual object handle can only be accessed by the creation connection. This make things hard for the collaboration of standalone tools based upon SAPI.

We can add a command line option "-sharedhandle" to explicitly allow the sharing of transient handles across connections.

**Comment by wcarthur1** [comment]
We agreed that this wasn't something we wanted to do.
