### ISSUE TITLE
Resource manager does not handle properly vendor specific commands

### ISSUE THREAD

**Issue by lbuczkow** [01org/TPM2.0-TSS#406]
GetCommandAttributes does not recognize vendor specific commands. TPMA_CC commandIndex is a 16 bit field and vendor specific commands are distinguished using V field. Attached patch fixes it.

[0001-getcommands.c-Fix-bug-in-support-for-vendor-specific.zip](https://github.com/01org/TPM2.0-TSS/files/986330/0001-getcommands.c-Fix-bug-in-support-for-vendor-specific.zip)

**Comment by flihp** [comment]
Hi @lbuczkow. Thanks for the patch and apologies for the code churn in related areas. Over the past few days I've been working to remove the resourcemgr in this code base and setting up a place for a replacement to live (https://github.com/01org/tpm2-abrmd). No doubt this new RM has plenty of bugs and probably the same one you've patched here :). Gimme a minute to take a look at your code and see how it translates to the new resource manager code base.

If you have the time feel free to poke around in the new resource manager code. As always, we're gladly taking patches / pull requests.

**Comment by flihp** [comment]
resourcemgr has been removed, closing issue
