### ISSUE TITLE
Location of resource manager

### ISSUE THREAD

**Issue by khanhnt93** [01org/TPM2.0-TSS#417]
I am trying test TPM. I use tpm2.0-tools and TPM2.0-TSS to test some feautre of tpm and a tpm simulator. But I haven't found binary of resource manager and I checked when I built TPM2.0-TSS, resource manager didn't built.
So, is this project contain resource manager? If not, can you give me link of resource manager source code?

**Comment by liuqun** [comment]
use https://github.com/01org/tpm2_abrmd 

the official replacement of the legacy resourcemgr

(you can also checkout history version of resourcemgr from TPM2.0-TSS. plz try to use github to view commit  history )

**Comment by liuqun** [comment]
use https://github.com/01org/tpm2-abrmd

the official replacement of the legacy resourcemgr

(you can also checkout history version of resourcemgr from TPM2.0-TSS. plz try to use github to view commit history )

**Comment by khanhnt93** [comment]
Thank you!
