### ISSUE TITLE
Sample code for used password, policy, hmac to authorization

### ISSUE THREAD

**Issue by khanhnt93** [01org/TPM2.0-TSS#423]
I have been learning in tpm 1 mounth ago but I still haven't understand authorization. I don't know how to use password, policy, hmac to authorization, confused about session...
Can you give me some code show used that?
I am using tpm simulator for tpm chip.
Thank you very much.

**Comment by liuqun** [comment]
see https://github.com/01org/TPM2.0-TSS/blob/master/test/integration/start-auth-session.c

**Comment by flihp** [comment]
Thanks for getting some data on this thread @liuqun. I've been slowly chipping away at breaking tpmclient up into separate integration tests to make finding stuff like this a bit easier but it's a long slog. Over on the tpm2-abrmd repo I'm working on an HMAC auth integration test that may also be useful (once it works :slightly_frowning_face:).

Seems like your answer is pretty complete so I'mma close this thread. @khanhnt93 : feel free to open up a new one if you need to.
