### ISSUE TITLE
A Problem with Policy Session

### ISSUE THREAD

**Issue by YaHosoda** [01org/TPM2.0-TSS#424]
Hi
I have started a policy session and then CreatePrimary.
After that, I do FlushContext.  In this case, FlushContext
ends with 0xC1000 (TSS2_RESMGR_FIND_FAILED)
However, if I comment out CreatePrimary, FlushContext
ends successfully.
Is there any misuse of the policy session? 
Btw, I use the resource manager Version 1,0.

StartAuthSessionWithParams (&nvSession, ..... ,SE_POLICY)
........ 
rval = Tss2_Sys_CreatePrimary (sysContext, TPM_RH_OWNER, &sessionsData,
                                   &inSensitive, &inPublic, &outsideInfo,
                                     &creationPCR, ......
........
rval = Tss2_Sys_FlushContext (sysContext, nvSession_P->sessionHandle);

**Comment by wcarthur1** [comment]
I suspect that you didn't set the the continue session bit on the session attributes during your create primary command.  If that's not set the Tpm ends the session and the resource manager removes the session from its database.

**Comment by YaHosoda** [comment]
It work well with continue Session=1 set.
Thank you very much for your advice!

**Comment by wcarthur1** [comment]
You’re welcome.
