### ISSUE TITLE
Include test/tpmclient/tpmclient in make check

### ISSUE THREAD

**Issue by PeterHuewe** [01org/TPM2.0-TSS#442]
While trying to debug other stuff I was wondering whether it makes sense to include test/tpmclient/tpmclient in the make check target.

If added manually at the moment it only reports 1 successful test, which is of course not what we want.
Evaluating how we can achieve that it shows each subtest, I came across two possible solutions:
a)write a LOG_DRIVER that more or less copies the current (automake compatible) std-output to the trs file and handles the PASS/FAIL reporting
b) convert the output to the TAP protocol and use the standard tap driver provided by automake.

Both require some work(which I could do)

What do you think?

**Comment by flihp** [comment]
I've made some progress on a similar scenario: https://github.com/01org/TPM2.0-TSS/commit/99d41422b1b96dea39b118970a45bc7e6cf27695

My eventual goal is to break tpmclient up into individual test executables run by automake on `make check`. Running `tpmcilent` in the test harness is definitely an incremental step in this direction. The link above was the first step, the second is to either build another log compiler (your option 'a' above) specific to `tpmclient`, or to go straight to porting tpmclient over to use the existing one.

I was planning to skip the second log compiler and go straight to porting `tpmclient` over to `int-log-compiler.sh`. This requires a bit of work though, specifically replacing the TCTI tests in `tpmclient` with unit tests (which is where they belong).

I'm about to take on the automated coverity scans (already done for the tpm2-abrmd). This was the next thing I was going to dig into. Any thing you're willing to do to move the code base in this direction would be much appreciated.

**Comment by flihp** [comment]
In PR #467 I've migrated the `tpmclient` executable to be run under the integration test harness. This has been merged back into master as well. IMHO that should answer this question definitively. Now comes the task of decomposing it into individual integration tests.
