### ISSUE TITLE
Tss2_Sys_Initialize: missing some RC values implementation.

### ISSUE THREAD

**Issue by juliantrzeciak** [01org/TPM2.0-TSS#46]
Current implementation of Tss2_Sys_Initialize() in https://github.com/01org/TPM2.0-TSS/blob/master/sysapi/sysapi/ContextManagement.c

according to:
http://www.trustedcomputinggroup.org/files/static_page_files/28CE28FA-1A4B-B294-D0A965038809FE9B/TSS%20system%20API%2001.pdf
TSS System Level API and TPM Command
Transmission Interface Specification
Family "2.0"
Level 00, Revision 01.00
26 January 2015

page 32
misses following RC values:
```
TSS2_SYS_RC_INSUFFICIENT_CONTEXT: if for any reason there’s not enough memory.
TSS2_SYS_RC_BAD_VALUE: if any parameter has a bad value.
TSS2_SYS_RC_BAD_REFERENCE: if any of sysContext is a NULL pointer.
TSS2_SYS_RC_BAD_TCTI_STRUCTURE: if the implementation checks the TCTI function pointers and
any of the essential ones (transmit and receive) are set to NULL.
Any TPM or TCTI errors that could result from GetCapability calls that are made to get TPM version info.
TSS2_SYS_RC_INCOMPATIBLE_TCTI: unknown or unusable TCTI version.
```
Any plans in this subject?

**Comment by wcarthur1** [comment]
Julian,

Good catch--yes, we missed those.  Not sure when I’ll get to this.  If you want, take a try at it yourself.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by juliantrzeciak** [comment]
Will,

I'll take a try.

There may be another candidates, ex: *Tss2_Sys_GetCpBuffer* misses some trivial null pointer checks.

Do you prefer to have separate issue per function?

**Comment by wcarthur1** [comment]
Whatever is easiest for you.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by juliantrzeciak** [comment]
log4fix: another candidate: Tss2_Sys_GetRpBuffer misses some trivial null pointer checks.

**Comment by wcarthur1** [comment]
Julian,

Did you ever do anything on this?  If not, I'll take it.

Will

**Comment by juliantrzeciak** [comment]
Will,
Please take it.
Thanks,
Julian

2015-11-02 23:22 GMT+01:00 wcarthur1 <notifications@github.com>:

**Comment by wcarthur1** [comment]
Julian,

I fixed the issues and added tests for the various cases.   Can you review my pull request?

Will

**Comment by wcarthur1** [comment]
Julian,

I goofed--my changes got merged into the main trunk as part of another change.  Please review the changes in commit  c7c4a127fbcfb5a2a3612b80b3ec3ea550e225e6.

Will

**Comment by juliantrzeciak** [comment]
done.
thanks

**Comment by wcarthur1** [comment]
So, can I close this issue?

**Comment by juliantrzeciak** [comment]
yes

2015-11-03 19:26 GMT+01:00 wcarthur1 <notifications@github.com>:

**Comment by juliantrzeciak** [comment]
Will,

Spec for Tss2_Sys_Initialize allows null pointer for tcti and abi, with further info what if.

Sorry for pointing it late.

Regards,
j

**Comment by wcarthur1** [comment]
Julian,

That’s been fixed in a more recent version of the spec.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101
