### ISSUE TITLE
make fails if configured without --enable-unit

### ISSUE THREAD

**Issue by PeterHuewe** [01org/TPM2.0-TSS#460]
Steps to reproduce:
./configure
 LANG=C make -j24
/bin/sh ./libtool  --tag=CC   --mode=link gcc -I./include -I./sysapi/include -I./marshal -Wall -Werror -std=gnu99 -Wformat -Wformat-security -fstack-protector-all -fpic -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wno-missing-braces -g -O2 -Wl,--version-script=./lib/libmarshal.map  -o marshal/libmarshal.la -rpath /usr/local/lib marshal/base-types.lo log/log.lo  
make: *** No rule to make target 'sysapi/sysapi_util/changeEndian.c', needed by 'sysapi/sysapi_util/changeEndian.lo'.  Stop.
make: *** Waiting for unfinished jobs....

**Comment by tstruk** [comment]
Hi Peter,
The changeEndian.c file has been removed in commit
https://github.com/01org/TPM2.0-TSS/commit/8203a37525bbd34d4416810c999bc9f73e9465ff
Could you run:
./bootstrap && make clean && make

**Comment by PeterHuewe** [comment]
Yes that worked - sorry for the confusion.

**Comment by flihp** [comment]
I'm starting to think that the make variables generated by the bootstrap script have a greater potential for harm than good. Saves a few key strokes in tracking source files in the makefile.am but costs more if you add / remove a file to the project and forget to run `./bootstrap`. I've forgotten about this in the past and spent minutes running in circles.

**Comment by tstruk** [comment]
What about this https://github.com/01org/TPM2.0-TSS/pull/461

**Comment by flihp** [comment]
Took a look at #461 and I really want to hate it but it makes a lot of sense :smile:. The only alternative I can come up with is manually tracking all source files in the `Makefile.am` directly. Will this execute 'git ls-files' every time 'make' is run?

**Comment by tstruk** [comment]
On 07/23/2017 05:01 PM, Philip Tricca wrote:
> Took a look at #461 <https://github.com/01org/TPM2.0-TSS/pull/461> and I really want to hate it but it makes a lot of sense 😄. The only alternative I can come up with is manually tracking all source files in the |Makefile.am| directly. Will this execute 'git ls-files' every time 'make' is run?-- 

Yes, it will execute 'git ls-files' on every make and if any file is added or removed it will
trigger ./bootstrap && make clean

**Comment by flihp** [comment]
Just saw that you added me as a reviewer on #461 so we can take the conversation over to the PR.

**Comment by PeterHuewe** [comment]
Does it work without git?
Peter
--

**Comment by tstruk** [comment]
On 07/24/2017 08:47 AM, Peter Huewe wrote:
> Does it work without git?

No, It needs the whole git repo.


-- 
Tadeusz
