### ISSUE TITLE
Docker file uses obsolete simulator make targets

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#468]
Hi @pdxjohnny. Sorry to do this to you but I just merged PR #459 and it removes the make targets to build / start / stop the simulator. The usage of these targets has also been removed from the .travis.yml file. Any chance I can get you to fixup the Docker file?

**Comment by pdxjohnny** [comment]
Hell yes! I'll get do that

**Comment by flihp** [comment]
resolved by #469
