### ISSUE TITLE
update algorithm identifiers.

### ISSUE THREAD

**Issue by williamcroberts** [01org/TPM2.0-TSS#476]
Update the comment in implementation.h so that table 3 of https://trustedcomputinggroup.org/wp-content/uploads/TCG_Algorithm_Registry_Rev_1.24.pdf is referenced.

Also update missing identifiers, like: TPM_ALG_SHA3_256. It appears that algs 0x27 -0x29 are missing.

Noticed from #475

**Comment by flihp** [comment]
I Just merged #373 since we won't be releasing from master till the new header spec is published and the patch can't hurt anything. Closing this along with it.
