### ISSUE TITLE
Tss2_Sys_GetRspAuths issues

### ISSUE THREAD

**Issue by juliantrzeciak** [01org/TPM2.0-TSS#50]
file: https://github.com/01org/TPM2.0-TSS/blob/master/sysapi/sysapi/authorizations.c 
commit: https://github.com/01org/TPM2.0-TSS/commit/ca8e7f3c705553f95e6ecafe96b291ab57dbb71f)

**1. missing oversize check TSS2_SYS_RC_INVALID_SESSIONS**
for hmac at line 201

**2. skip rspAuth extraction when destination pointer ==0**
according to:
http://www.trustedcomputinggroup.org/files/static_page_files/28CE28FA-1A4B-B294-D0A965038809FE9B/TSS%20system%20API%2001.pdf
TSS System Level API and TPM Command
Transmission Interface Specification
Family "2.0"
Level 00, Revision 01.00
26 January 2015

page 41
>8.7.4.2 Tss2_Sys_GetRspAuths
>...
>This function gets the response authorization data from the sysContext. If an element in the
>rspAuthArray->rspAuths array is NULL, that authorization is skipped in the sysContext.

Scenario: 
sysContext contains 3 rspAuths, 
rspAuthArray->rspAuths[1] == 0 // element is NULL but others not
Tss2_Sys_GetRspAuths(sysContext, rspAuthArray) 
**result**: rspAuthArray->rspAuths[2] is not populated with third rspAuth from sysContext
**expected result**: 
rspAuthArray->rspAuths[0] is populated with first rspAuth from sysContext
rspAuthArray->rspAuths[1] extraction skipped
rspAuthArray->rspAuths[2] is populated with third rspAuth from sysContext

Let me know If I understand it correctly, then I can provide a fix.

**3. TSS2_RC_SUCCESS when rspAuthsArray == NULL**
according to doc it should be:
>TSS2_SYS_RC_BAD_REFERENCE: if sysContext or rspAuthsArray are NULL

update for doc?

**4. not implemented TSS2_SYS_RC_BAD_VALUE: if rspAuthsArray.authsCount is 0**
its covered by either by 
>TSS2_RC_SUCCESS when SYS_CONTEXT->authsCount ==0

or
>TSS2_SYS_RC_INVALID_SESSIONS when ( rspAuthsArray->rspAuthsCount != SYS_CONTEXT->authsCount )

update for doc?

**Comment by wcarthur1** [comment]
Julian,

I've added tests and fixed all the issues with getRspauths. 
Can you look at my pull request #65 and approve them for merging?

Thanks,
Will

**Comment by juliantrzeciak** [comment]
Will,

I think current solution is against spec.
Plase double check scenario: 2. skip rspAuth extraction when destination pointer ==0

when when there is a null pointer to TPMS_AUTH_RESPONSE within TSS2_SYS_RSP_AUTHS  *rspAuthsArray

In such case given null-memeber within rspAuthsArray should be gracefully skipped in extracting rsp auths.

Best Regards,
Julian

**Comment by wcarthur1** [comment]
Julian,

This was actually an error in my checkin comments.  The code and tests are right, the comment was wrong.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by wcarthur1** [comment]
Julian,

I fixed both the commit comment for GetRspAuths and the issue you pointed out with SetCmdAuths.

Please review the changes and accept the pull request if it’s okay.

Thanks!

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

From: Arthur, Will C
Sent: Wednesday, November 11, 2015 9:59 AM
To: '01org/TPM2.0-TSS' <reply@reply.github.com>
Subject: RE: [TPM2.0-TSS] Tss2_Sys_GetRspAuths issues (#50)

Julian,

This was actually an error in my checkin comments.  The code and tests are right, the comment was wrong.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by juliantrzeciak** [comment]
Will,

Accept, please close this one.

Best Regards,
Julian

**Comment by wcarthur1** [comment]
I assume you meant close both #50 and #51.  Is that correct?

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by juliantrzeciak** [comment]
Yes. Thanks.

2015-11-12 14:22 GMT+01:00 wcarthur1 <notifications@github.com>:
