### ISSUE TITLE
sysapi build failure in window: NMAKE: expanded cmdline too long

### ISSUE THREAD

**Issue by gwei3** [01org/TPM2.0-TSS#64]
1>NMAKE : fatal error U1095: expanded command line 'C:\"Program Files (x86)"\"Microsoft Visual Studio 12.0"\VC\BIN\lib /NOLOGO /OUT:.\lib\debug\tpm.lib .\lib\debug\authorizations.obj  .\lib\debug\ContextManagement.obj  .\lib\debug\DecryptParam.obj  .\lib\debug\EncryptParam.obj  .\lib\debug\execute.obj  .\lib\debug\Finalize.obj  .\lib\debug\GetCommandCode.obj  .\lib\debug\GetCpBuffer.obj  .\lib\debug\GetRpBuffer.obj  .\lib\debug\GetTctiContext.obj  .\lib\debug\Tss2_Sys_ActivateCredential.obj  .\lib\debug\Tss2_Sys_Certify.obj  .\lib\debug\Tss2_Sys_CertifyCreation.obj  .\lib\debug\Tss2_Sys_ChangeEPS.obj  .\lib\debug\Tss2_Sys_ChangePPS.obj  .\lib\debug\Tss2_Sys_Clear.obj  .\lib\debug\Tss2_Sys_ClearControl.obj  .\lib\debug\Tss2_Sys_ClockRateAdjust.obj  .\lib\debug\Tss2_Sys_ClockSet.obj  .\lib\debug\Tss2_Sys_Commit.obj  .\lib\debug\Tss2_Sys_ContextLoad.obj  .\lib\debug\Tss2_Sys_ContextSave.obj  .\lib\debug\Tss2_Sys_Create.obj  .\lib\debug\Tss2_Sys_CreatePrimary.obj  .\lib\debug\Tss2_Sys_DictionaryAttackLockReset.obj  .\lib\debug\Tss2_Sys_DictionaryAttackParameters.obj  .\lib\debug\Tss2_Sys_Duplicate.obj  .\lib\debug\Tss2_Sys_ECC_Parameters.obj  .\lib\debug\Tss2_Sys_ECDH_KeyGen.obj  .\lib\debug\Tss2_Sys_ECDH_ZGen.obj  .\lib\debug\Tss2_Sys_EC_Ephemeral.obj  .\lib\debug\Tss2_Sys_EncryptDecrypt.obj  .\lib\debug\Tss2_Sys_EventSequenceComplete.obj  .\lib\debug\Tss2_Sys_EvictControl.obj  .\lib\debug\Tss2_Sys_FieldUpgradeData.obj  .\lib\debug\Tss2_Sys_FieldUpgradeStart.obj  .\lib\debug\Tss2_Sys_FirmwareRead.obj  .\lib\debug\Tss2_Sys_FlushContext.obj  .\lib\debug\Tss2_Sys_GetCapability.obj  .\lib\debug\Tss2_Sys_GetCommandAuditDigest.obj  .\lib\debug\Tss2_Sys_GetRandom.obj  .\lib\debug\Tss2_Sys_GetSessionAuditDigest.obj  .\lib\debug\Tss2_Sys_GetTestResult.obj  .\lib\debug\Tss2_Sys_GetTime.obj  .\lib\debug\Tss2_Sys_Hash.obj  .\lib\debug\Tss2_Sys_HashSequenceStart.obj  .\lib\debug\Tss2_Sys_HierarchyChangeAuth.obj  .\lib\debug\Tss2_Sys_HierarchyControl.obj  .\lib\debug\Tss2_Sys_HMAC.obj  .\lib\debug\Tss2_Sys_HMAC_Start.obj  .\lib\debug\Tss2_Sys_Import.obj  .\lib\debug\Tss2_Sys_IncrementalSelfTest.obj  .\lib\debug\Tss2_Sys_Load.obj  .\lib\debug\Tss2_Sys_LoadExternal.obj  .\lib\debug\Tss2_Sys_MakeCredential.obj  .\lib\debug\Tss2_Sys_NV_Certify.obj  .\lib\debug\Tss2_Sys_NV_ChangeAuth.obj  .\lib\debug\Tss2_Sys_NV_DefineSpace.obj  .\lib\debug\Tss2_Sys_NV_Extend.obj  .\lib\debug\Tss2_Sys_NV_GlobalWriteLock.obj  .\lib\debug\Tss2_Sys_NV_Increment.obj  .\lib\debug\Tss2_Sys_NV_Read.obj  .\lib\debug\Tss2_Sys_NV_ReadLock.obj  .\lib\debug\Tss2_Sys_NV_ReadPublic.obj  .\lib\debug\Tss2_Sys_NV_SetBits.obj  .\lib\debug\Tss2_Sys_NV_UndefineSpace.obj  .\lib\debug\Tss2_Sys_NV_UndefineSpaceSpecial.obj  .\lib\debug\Tss2_Sys_NV_Write.obj  .\lib\debug\Tss2_Sys_NV_WriteLock.obj  .\lib\debug\Tss2_Sys_ObjectChangeAuth.obj  .\lib\debug\Tss2_Sys_PCR_Allocate.obj  .\lib\debug\Tss2_Sys_PCR_Event.obj  .\lib\debug\Tss2_Sys_PCR_Extend.obj  .\lib\debug\Tss2_Sys_PCR_Read.obj  .\lib\debug\Tss2_Sys_PCR_Reset.obj  .\lib\debug\Tss2_Sys_PCR_SetAuthPolicy.obj  .\lib\debug\Tss2_Sys_PCR_SetAuthValue.obj  .\lib\debug\Tss2_Sys_PolicyAuthorize.obj  .\lib\debug\Tss2_Sys_PolicyAuthValue.obj  .\lib\debug\Tss2_Sys_PolicyCommandCode.obj  .\lib\debug\Tss2_Sys_PolicyCounterTimer.obj  .\lib\debug\Tss2_Sys_PolicyCpHash.obj  .\lib\debug\Tss2_Sys_PolicyDuplicationSelect.obj  .\lib\debug\Tss2_Sys_PolicyGetDigest.obj  .\lib\debug\Tss2_Sys_PolicyLocality.obj  .\lib\debug\Tss2_Sys_PolicyNameHash.obj  .\lib\debug\Tss2_Sys_PolicyNV.obj  .\lib\debug\Tss2_Sys_PolicyNVWritten.obj  .\lib\debug\Tss2_Sys_PolicyOR.obj  .\lib\debug\Tss2_Sys_PolicyPassword.obj  .\lib\debug\Tss2_Sys_PolicyPCR.obj  .\lib\debug\Tss2_Sys_PolicyPhysicalPresence.obj  .\lib\debug\Tss2_Sys_PolicyRestart.obj  .\lib\debug\Tss2_Sys_PolicySecret.obj  .\lib\debug\Tss2_Sys_PolicySigned.obj  .\lib\debug\Tss2_Sys_PolicyTicket.obj  .\lib\debug\Tss2_Sys_PP_Commands.obj  .\lib\debug\Tss2_Sys_Quote.obj  .\lib\debug\Tss2_Sys_ReadClock.obj  .\lib\debug\Tss2_Sys_ReadPublic.obj  .\lib\debug\Tss2_Sys_Rewrap.obj  .\lib\debug\Tss2_Sys_RSA_Decrypt.obj  .\lib\debug\Tss2_Sys_RSA_Encrypt.obj  .\lib\debug\Tss2_Sys_SelfTest.obj  .\lib\debug\Tss2_Sys_SequenceComplete.obj  .\lib\debug\Tss2_Sys_SequenceUpdate.obj  .\lib\debug\Tss2_Sys_SetAlgorithmSet.obj  .\lib\debug\Tss2_Sys_SetCommandCodeAuditStatus.obj  .\lib\debug\Tss2_Sys_SetPrimaryPolicy.obj  .\lib\debug\Tss2_Sys_Shutdown.obj  .\lib\debug\Tss2_Sys_Sign.obj  .\lib\debug\Tss2_Sys_StartAuthSession.obj  .\lib\debug\Tss2_Sys_Startup.obj  .\lib\debug\Tss2_Sys_StirRandom.obj  .\lib\debug\Tss2_Sys_TestParms.obj  .\lib\debug\Tss2_Sys_Unseal.obj  .\lib\debug\Tss2_Sys_Vendor_TCG_Test.obj  .\lib\debug\Tss2_Sys_VerifySignature.obj  .\lib\debug\Tss2_Sys_ZGen_2Phase.obj  .\lib\debug\changeEndian.obj  .\lib\debug\checkoverflow.obj  .\lib\debug\CommandUtil.obj  .\lib\debug\CompareSizedByteBuffer.obj  .\lib\debug\ConcatSizedByteBuffer.obj  .\lib\debug\copymem.obj  .\lib\debug\CopySessionData.obj  .\lib\debug\debug.obj  .\lib\debug\GetDigestSize.obj  .\lib\debug\GetNumHandles.obj  .\lib\debug\marshal_simple_tpm2b.obj  .\lib\debug\Marshal_TPM2B_ECC_POINT.obj  .\lib\debug\Marshal_TPM2B_NV_PUBLIC.obj  .\lib\debug\Marshal_TPM2B_PUBLIC.obj  .\lib\debug\Marshal_TPM2B_SENSITIVE.obj  .\lib\debug\Marshal_TPM2B_SENSITIVE_CREATE.obj  .\lib\debug\Marshal_TPMA_ALGORITHM.obj  .\lib\debug\Marshal_TPMA_LOCALITY.obj  .\lib\debug\Marshal_TPMA_NV.obj  .\lib\debug\Marshal_TPMA_OBJECT.obj  .\lib\debug\Marshal_TPMA_SESSION.obj  .\lib\debug\Marshal_TPML_ALG.obj  .\lib\debug\Marshal_TPML_CC.obj  .\lib\debug\Marshal_TPML_DIGEST.obj  .\lib\debug\Marshal_TPML_DIGEST_VALUES.obj  .\lib\debug\Marshal_TPML_PCR_SELECTION.obj  .\lib\debug\Marshal_TPMS_AUTH_COMMAND.obj  .\lib\debug\Marshal_TPMS_CLOCK_INFO.obj  .\lib\debug\Marshal_TPMS_CONTEXT.obj  .\lib\debug\Marshal_TPMS_CONTEXT_DATA.obj  .\lib\debug\Marshal_TPMS_ECC_PARMS.obj  .\lib\debug\Marshal_TPMS_ECC_POINT.obj  .\lib\debug\Marshal_TPMS_EMPTY.obj  .\lib\debug\Marshal_TPMS_KEYEDHASH_PARMS.obj  .\lib\debug\Marshal_TPMS_NV_PUBLIC.obj  .\lib\debug\Marshal_TPMS_PCR_SELECT.obj  .\lib\debug\Marshal_TPMS_PCR_SELECTION.obj  .\lib\debug\Marshal_TPMS_RSA_PARMS.obj  .\lib\debug\Marshal_TPMS_SCHEME_ECDAA.obj  .\lib\debug\Marshal_TPMS_SCHEME_HASH.obj  .\lib\debug\Marshal_TPMS_SCHEME_XOR.obj  .\lib\debug\Marshal_TPMS_SENSITIVE_CREATE.obj  .\lib\debug\Marshal_TPMS_SIGNATURE_ECC.obj  .\lib\debug\Marshal_TPMS_SIGNATURE_RSA.obj  .\lib\debug\Marshal_TPMS_SYMCIPHER_PARMS.obj  .\lib\debug\Marshal_TPMS_TIME_INFO.obj  .\lib\debug\Marshal_TPMT_ECC_SCHEME.obj  .\lib\debug\Marshal_TPMT_HA.obj  .\lib\debug\Marshal_TPMT_KDF_SCHEME.obj  .\lib\debug\Marshal_TPMT_KEYEDHASH_SCHEME.obj  .\lib\debug\Marshal_TPMT_PUBLIC.obj  .\lib\debug\Marshal_TPMT_PUBLIC_PARMS.obj  .\lib\debug\Marshal_TPMT_RSA_DECRYPT.obj  .\lib\debug\Marshal_TPMT_RSA_SCHEME.obj  .\lib\debug\Marshal_TPMT_SENSITIVE.obj  .\lib\debug\Marshal_TPMT_SIGNATURE.obj  .\lib\debug\Marshal_TPMT_SIG_SCHEME.obj  .\lib\debug\Marshal_TPMT_SYM_DEF.obj  .\lib\debug\Marshal_TPMT_SYM_DEF_OBJECT.obj  .\lib\debug\Marshal_TPMT_TK_AUTH.obj  .\lib\debug\Marshal_TPMT_TK_CREATION.obj  .\lib\debug\Marshal_TPMT_TK_HASHCHECK.obj  .\lib\debug\Marshal_TPMT_TK_VERIFIED.obj  .\lib\debug\Marshal_TPMU_ASYM_SCHEME.obj  .\lib\debug\Marshal_TPMU_HA.obj  .\lib\debug\Marshal_TPMU_KDF_SCHEME.obj  .\lib\debug\Marshal_TPMU_PUBLIC_ID.obj  .\lib\debug\Marshal_TPMU_PUBLIC_PARMS.obj  .\lib\debug\Marshal_TPMU_SCHEME_KEYEDHASH.obj  .\lib\debug\Marshal_TPMU_SENSITIVE_COMPOSITE.obj  .\lib\debug\Marshal_TPMU_SIGNATURE.obj  .\lib\debug\Marshal_TPMU_SIG_SCHEME.obj  .\lib\debug\Marshal_TPMU_SYM_KEY_BITS.obj  .\lib\debug\Marshal_TPMU_SYM_MODE.obj  .\lib\debug\marshal_uint16.obj  .\lib\debug\marshal_uint32.obj  .\lib\debug\marshal_uint64.obj  .\lib\debug\marshal_uint8.obj  .\lib\debug\unmarshal_simple_tpm2b.obj  .\lib\debug\Unmarshal_TPM2B_ECC_POINT.obj  .\lib\debug\Unmarshal_TPM2B_NV_PUBLIC.obj  .\lib\debug\Unmarshal_TPM2B_PUBLIC.obj  .\lib\debug\Unmarshal_TPM2B_SENSITIVE.obj  .\lib\debug\Unmarshal_TPMA_ALGORITHM.obj  .\lib\debug\Unmarshal_TPMA_CC.obj  .\lib\debug\Unmarshal_TPMA_LOCALITY.obj  .\lib\debug\Unmarshal_TPMA_NV.obj  .\lib\debug\Unmarshal_TPMA_OBJECT.obj  .\lib\debug\Unmarshal_TPMA_PERMANENT.obj  .\lib\debug\Unmarshal_TPMA_SESSION.obj  .\lib\debug\Unmarshal_TPMA_STARTUP_CLEAR.obj  .\lib\debug\Unmarshal_TPML_ALG.obj  .\lib\debug\Unmarshal_TPML_ALG_PROPERTY.obj  .\lib\debug\Unmarshal_TPML_CC.obj  .\lib\debug\Unmarshal_TPML_CCA.obj  .\lib\debug\Unmarshal_TPML_DIGEST.obj  .\lib\debug\Unmarshal_TPML_DIGEST_VALUES.obj  .\lib\debug\Unmarshal_TPML_ECC_CURVE.obj  .\lib\debug\Unmarshal_TPML_HANDLE.obj  .\lib\debug\Unmarshal_TPML_PCR_SELECTION.obj  .\lib\debug\Unmarshal_TPML_TAGGED_PCR_PROPERTY.obj  .\lib\debug\Unmarshal_TPML_TAGGED_TPM_PROPERTY.obj  .\lib\debug\Unmarshal_TPMS_ALGORITHM_DESCRIPTION.obj  .\lib\debug\Unmarshal_TPMS_ALGORITHM_DETAIL_ECC.obj  .\lib\debug\Unmarshal_TPMS_ALG_PROPERTY.obj  .\lib\debug\Unmarshal_TPMS_ATTEST.obj  .\lib\debug\Unmarshal_TPMS_AUTH_RESPONSE.obj  .\lib\debug\Unmarshal_TPMS_CAPABILITY_DATA.obj  .\lib\debug\Unmarshal_TPMS_CERTIFY_INFO.obj  .\lib\debug\Unmarshal_TPMS_CLOCK_INFO.obj  .\lib\debug\Unmarshal_TPMS_COMMAND_AUDIT_INFO.obj  .\lib\debug\Unmarshal_TPMS_CONTEXT.obj  .\lib\debug\Unmarshal_TPMS_CONTEXT_DATA.obj  .\lib\debug\Unmarshal_TPMS_CREATION_DATA.obj  .\lib\debug\Unmarshal_TPMS_CREATION_INFO.obj  .\lib\debug\Unmarshal_TPMS_ECC_PARMS.obj  .\lib\debug\Unmarshal_TPMS_ECC_POINT.obj  .\lib\debug\Unmarshal_TPMS_EMPTY.obj  .\lib\debug\Unmarshal_TPMS_KEYEDHASH_PARMS.obj  .\lib\debug\Unmarshal_TPMS_NV_CERTIFY_INFO.obj  .\lib\debug\Unmarshal_TPMS_NV_PUBLIC.obj  .\lib\debug\Unmarshal_TPMS_PCR_SELECT.obj  .\lib\debug\Unmarshal_TPMS_PCR_SELECTION.obj  .\lib\debug\Unmarshal_TPMS_QUOTE_INFO.obj  .\lib\debug\Unmarshal_TPMS_RSA_PARMS.obj  .\lib\debug\Unmarshal_TPMS_SCHEME_ECDAA.obj  .\lib\debug\Unmarshal_TPMS_SCHEME_HASH.obj  .\lib\debug\Unmarshal_TPMS_SCHEME_XOR.obj  .\lib\debug\Unmarshal_TPMS_SESSION_AUDIT_INFO.obj  .\lib\debug\Unmarshal_TPMS_SIGNATURE_ECC.obj  .\lib\debug\Unmarshal_TPMS_SIGNATURE_RSA.obj  .\lib\debug\Unmarshal_TPMS_SYMCIPHER_PARMS.obj  .\lib\debug\Unmarshal_TPMS_TAGGED_PCR_SELECT.obj  .\lib\debug\Unmarshal_TPMS_TAGGED_PROPERTY.obj  .\lib\debug\Unmarshal_TPMS_TIME_ATTEST_INFO.obj  .\lib\debug\Unmarshal_TPMS_TIME_INFO.obj  .\lib\debug\Unmarshal_TPMT_ECC_SCHEME.obj  .\lib\debug\Unmarshal_TPMT_HA.obj  .\lib\debug\Unmarshal_TPMT_KDF_SCHEME.obj  .\lib\debug\Unmarshal_TPMT_KEYEDHASH_SCHEME.obj  .\lib\debug\Unmarshal_TPMT_PUBLIC.obj  .\lib\debug\Unmarshal_TPMT_PUBLIC_PARMS.obj  .\lib\debug\Unmarshal_TPMT_RSA_DECRYPT.obj  .\lib\debug\Unmarshal_TPMT_RSA_SCHEME.obj  .\lib\debug\Unmarshal_TPMT_SENSITIVE.obj  .\lib\debug\Unmarshal_TPMT_SIGNATURE.obj  .\lib\debug\Unmarshal_TPMT_SIG_SCHEME.obj  .\lib\debug\Unmarshal_TPMT_SYM_DEF.obj  .\lib\debug\Unmarshal_TPMT_SYM_DEF_OBJECT.obj  .\lib\debug\Unmarshal_TPMT_TK_AUTH.obj  .\lib\debug\Unmarshal_TPMT_TK_CREATION.obj  .\lib\debug\Unmarshal_TPMT_TK_HASHCHECK.obj  .\lib\debug\Unmarshal_TPMT_TK_VERIFIED.obj  .\lib\debug\Unmarshal_TPMU_ASYM_SCHEME.obj  .\lib\debug\Unmarshal_TPMU_ATTEST.obj  .\lib\debug\Unmarshal_TPMU_CAPABILITIES.obj  .\lib\debug\Unmarshal_TPMU_HA.obj  .\lib\debug\Unmarshal_TPMU_KDF_SCHEME.obj  .\lib\debug\Unmarshal_TPMU_PUBLIC_ID.obj  .\lib\debug\Unmarshal_TPMU_PUBLIC_PARMS.obj  .\lib\debug\Unmarshal_TPMU_SCHEME_KEYEDHASH.obj  .\lib\debug\Unmarshal_TPMU_SENSITIVE_COMPOSITE.obj  .\lib\debug\Unmarshal_TPMU_SIGNATURE.obj  .\lib\debug\Unmarshal_TPMU_SIG_SCHEME.obj  .\lib\debug\Unmarshal_TPMU_SYM_KEY_BITS.obj  .\lib\debug\Unmarshal_TPMU_SYM_MODE.obj  .\lib\debug\unmarshal_uint16.obj  .\lib\debug\unmarshal_uint32.obj  .\lib\debug\unmarshal_uint64.obj  .\lib\debug\unmarshal_uint8.obj  ' too long
1>  Stop.
1>NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\nmake.exe"' : return code '0x2'
1>  Stop.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.MakeFile.Targets(38,5): error MSB3073: The command "nmake /F windows.mak Debug" exited with code 2.

**Comment by BenyuXu** [comment]
Hi, Jimmy
maybe you could try like below:
1.     open a command window,
2.	subst K:  “C:\Program Files (x86)\Microsoft Visual Studio 11.0”,
3.	run “k:\VC\bin\vcvars.bat “ ,
4.	in computer -> properties -> advanced systerm setting -> environment varibles, add a new value:  TSSTOOLS_PATH=K:

FYI

**Comment by flihp** [comment]
Do we intend to support nmake? Has anyone successfully built this code using nmake before?

**Comment by wcarthur1** [comment]
For command line builds, I use msbuild from the project’s root dir:
>msbuild tss.sln

I think you have to be in a VS 2010 command prompt window OR a command window from which you’ve run the following:
call %TSSTOOLS_PATH%\vc\bin\vcvars32.bat

I don’t know if nmake works—haven’t tried it.  I’d suggest msbuild.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by gwei3** [comment]
msbuild tss.sln will report similar error.

the issue is how to build the tpm20lib-tpm project. that project is using nmake to build, isn't it?

**Comment by wcarthur1** [comment]
I guess I got around this by doing the following:

subst k: c:\"Program Files (x86)\\Microsoft Visual Studio 11.0"
call k:\vc\bin\vcvars32.bat"
set TSSTOOLS_PATH=k:"\VC\bin"

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by gwei3** [comment]
I am using VS2012, and it seems like the TSSTOOLS_PATH variable doesn't impact it at all - I tried.

IMHO, the expanded NMAKE cmdline is now 11446 chars, just reduce tens of chars in the beginning should not make sense for fix it.

Have you ever build the tip in window? and have you ever tried VS2012?

Maybe I should try VS2011 later...

**Comment by theopolis** [comment]
Maybe a can of worms, but CMake is very nice for support cross-platform builds. You can then generate your Makefile/SLNs/NMake files, etc. ;)

**Comment by gwei3** [comment]
thanks Teddy, will give it a try when possible.

**Comment by flihp** [comment]
The build instructions state that VS2010 is the supported VS version and as @gwei3 says he's using VS2012. IMO this issue should be closed as "won't fix". If we'd like to upgrade to a newer version of VS that should probably go into a new ticket. If anyone disagrees with this please feel free to reopen the issue.

**Comment by theopolis** [comment]
I agree!

(another plug!) If you get CI building for VS you can [explicitly choose/test](https://github.com/01org/TPM2.0-TSS/pull/97/files#diff-180360612c6b8c4ed830919bbb4dd459R3) the versions. ;)

I can also add some anecdotal memories from trying VS 15 and having the build bark.
