### ISSUE TITLE
extract and share common code from tpmtest & tpmclient

### ISSUE THREAD

**Issue by gwei3** [01org/TPM2.0-TSS#91]
To keep the test cases in sync and minimize the maintanance effort, we need to let tpmtest & tpmclient share more common code.

**Comment by theopolis** [comment]
:+1:

**Comment by flihp** [comment]
This sounds like a good idea but I'm not sure I understand what you mean by 'extract'. Can you clarify @gwei3?

**Comment by gwei3** [comment]
For example, we can move the duplicated utility functions into test/common/utilities/ folder, and move the duplicated test case functions into test/common/cases/ folder, then clean up both tpmclient & tpmtest to be as small as possible to include only different flow handling code for how to execute the cases.

**Comment by flihp** [comment]
Oh I see. I'm all for separating out individual test cases. Even better would be porting them over to a test framework to get a consistent structure and automate test execution

**Comment by theopolis** [comment]
Google test (gtest) provides a ton of test harness features. You end up including it alongside source or within a submodule but it'll save a ton of time. Test reordering, exception/stack reporting, filtering, etc; if it's ever appropriate to include benchmarking, Google benchmark works in tandem with Gtest too.

**Comment by flihp** [comment]
I went with the nuclear option here and just removed tpmtest. Not the ideal solution but with 0 progress on this in the last 6 months I wasn't hopeful that someone would show up with patches any time soon.
