### ISSUE TITLE
is the resource manager header intended for public consumption?

### ISSUE THREAD

**Issue by flihp** [01org/TPM2.0-TSS#95]
In going through the tpm2.0-tools build I'm trying to reverse engineer the dependencies it has on the TPM2.0-TSS code. One thing it's referencing directly is the resource manager header. AFAIK it's doing this to get at only a few status codes.

What's not entirely clear to me is whether or not this file is intended for public consumption. If it is we only need to decide where to install it so that's easy. But from my reading of the TAB/RM specification we reference in the README, it looks like this file may not be intended for public consumption. This would mean that the tpm2.0-tools shouldn't be touching it at all and that the code there needs to be fixed.

@wcarthur1 any thoughts on this?

**Comment by wcarthur1** [comment]
Philip,

Below…

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by flihp** [comment]
On the first point I was confusing the error levels that the tools are getting from the SAPI headers with the return codes defined in the RM header: https://github.com/01org/tpm2.0-tools/blob/master/sapi-tools/common.cpp#L202

I just did a quick test here and the tools are including the resource manager header but not actually using anything from it. Confusing: https://github.com/01org/tpm2.0-tools/blob/master/sapi-tools/common.cpp#L65

The last bit about the header being intended for public consumption seems to be cleared up by section 4 of the TAB/RM spec. These are the error levels that the tools consume, what I initially confused with error codes. TAB/RM error codes on the other hand are considered implementation specific.

So it's expected that client applications would be consuming the RM header to decode error codes, though these codes are not defined in the spec / are implementation specific. Also the name, location and contents of the header file are all implementation specific. Hopefully I'm not missing this too badly?

**Comment by wcarthur1** [comment]
Below…

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by flihp** [comment]
Great. Thanks for clearing that up. I'll be cleaning up / out the use of the RM header in the tools repo as part of this work. But back to my original question: To install the header or not?

From the data in this thread it sounds like:
1) There's nothing that says we can't / shouldn't.
2) From your last point it sounds like you believe that there's little value in doing so.

I guess I'd personally error on the side of providing too much information than not enough. Installing the header is probably a good idea just in case someone out there wants to do something with the error codes that the RM may return. Reasonable?

**Comment by wcarthur1** [comment]
Below…

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by flihp** [comment]
I'm happy to leave it as it is now without the header installed if that's what you would prefer. In digging through this it turns out the dependency from the tpm2.0-tools repo is easy to break since it was just including the header but not using anything from it. If there's a need in the future we can revisit this on demand.

Thanks again for the data.
